import {Injectable} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import {DateTime} from 'luxon';
import {schedule,addWorking,subtractWorking,workingMinutesBetween,type Task,type Calendar,type Dependency} from '@heec/scheduler';
import {DatabaseService} from '../database/database.service';
import {AuditService} from '../audit/audit.service';
import type {UserContext} from '../auth/request-context';
import {DomainError} from '../common/errors';
import {buildTask,buildDependency,toMinute} from '../schedule/mapper';
import {ExchangeStorage,stableHash,contentHash} from './storage';
import {parseExchange,durationMinutes,parseInstant} from './parser';
import {resolveCalendars} from './calendars';
import {compareTables} from './round-trip';
import {writeCsvPackage} from './csv-package';
import {writeCsv,writeXlsx,readTables} from './formats';
import {writeMspXml} from './msp-xml';
import {TASK_COLUMNS,EXTRA_COLUMNS,SCHEMA_VERSION,PARSER_VERSION,LIMITS,ExchangeParseError,type Issue,type ParseOptions,type ParsedExchange,type SheetRow} from './model';
import type {UploadDto,PreviewDto,CommitDto,ExportDto} from './dto';
interface Queryable{query(sql:string,params?:any[]):Promise<{rows:any[]}>}
const addIssue=(issues:Issue[],field:string,code:string,message:string,row=0,severity:Issue['severity']='error')=>issues.push({row,field,code,message,severity});
@Injectable()
export class ExchangeService{
 constructor(private db:DatabaseService,private audit:AuditService,private storage:ExchangeStorage){}
 private connection():Queryable{return{query:async(sql,params)=>({rows:await this.db.query(sql,params)})};}
 private async project(q:Queryable,ctx:UserContext,p:string,lock=false){const r=await q.query(`SELECT p.* FROM projects p WHERE p.id=$1 AND p.org_id=$2 AND p.archived_at IS NULL AND ($4 OR p.created_by=$3 OR p.pm_user_id=$3 OR EXISTS(SELECT 1 FROM project_members m WHERE m.project_id=p.id AND m.user_id=$3 AND m.archived_at IS NULL)) ${lock?'FOR UPDATE':''}`,[p,ctx.orgId,ctx.userId,ctx.roles.includes('Admin')]);if(!r.rows[0])throw DomainError.notFound('案件');return r.rows[0];}
 private async job(q:Queryable,ctx:UserContext,p:string,j:string,lock=false){await this.project(q,ctx,p);const r=await q.query(`SELECT * FROM import_jobs WHERE id=$1 AND project_id=$2 AND org_id=$3 AND archived_at IS NULL ${lock?'FOR UPDATE':''}`,[j,p,ctx.orgId]);if(!r.rows[0])throw DomainError.notFound('匯入工作');return r.rows[0];}
 private key(value:string|undefined){if(!value||value.length>200||!value.trim())throw DomainError.validation('須提供不超過200字的 Idempotency-Key');return value;}
 private async vector(q:Queryable,org:string,p:string,scope:{resourceIds:string[];calendarIds:string[]}){const tables=['project_tasks','task_dependencies','resource_assignments','baselines','external_id_map'];const data:any={};data.project=(await q.query('SELECT version,schedule_version,default_calendar_id,permit_filing_date FROM projects WHERE id=$1 AND org_id=$2',[p,org])).rows;for(const t of tables)data[t]=(await q.query(`SELECT id,version FROM ${t} WHERE project_id=$1 AND org_id=$2 ORDER BY id`,[p,org])).rows;for(const t of ['resources','resource_aliases','resource_calendars'])data[t]=(await q.query(`SELECT id,version FROM ${t} WHERE org_id=$1 AND ${t==='resources'?'id':'resource_id'}=ANY($2::uuid[]) ORDER BY id`,[org,scope.resourceIds])).rows;for(const t of ['calendars','calendar_working_days','calendar_exceptions'])data[t]=(await q.query(`SELECT id,version FROM ${t} WHERE org_id=$1 AND ${t==='calendars'?'id':'calendar_id'}=ANY($2::uuid[]) ORDER BY id`,[org,scope.calendarIds])).rows;return stableHash(data);}
 async upload(ctx:UserContext,p:string,bytes:Buffer,dto:UploadDto,key:string|undefined,correlation:string,asyncMode=false){
  const project=await this.project(this.connection(),ctx,p);key=this.key(key);if(bytes.length>LIMITS.bytes)throw new DomainError('validation','file_limit','檔案超過10 MiB',undefined,413);
  const metadata={...dto,timezone:dto.timezone??project.timezone};const hash=stableHash({file:contentHash(bytes),metadata});const old=await this.db.queryOne<any>('SELECT * FROM import_jobs WHERE project_id=$1 AND idempotency_key=$2',[p,key]);if(old){if(old.input_hash!==hash)throw DomainError.conflict('idempotency_conflict','相同key的檔案或選項不同');return this.publicJob(old);}
  const objectKey=await this.storage.write(bytes);let job:any;
  try{job=await this.db.transaction(async c=>{await this.project(c,ctx,p,true);const r=await c.query(`INSERT INTO import_jobs(org_id,project_id,source_type,object_key,locale,timezone,idempotency_key,input_hash,request_metadata,initiated_by,created_by,updated_by) VALUES($1,$2,$3,$4,'zh-TW',$5,$6,$7,$8,$9,$9,$9) RETURNING *`,[ctx.orgId,p,dto.format,objectKey,metadata.timezone,key,hash,JSON.stringify(metadata),ctx.userId]);await this.audit.write(c,ctx,{entityType:'import_job',entityId:r.rows[0].id,action:'upload',diff:{format:dto.format,file_hash:contentHash(bytes)},correlationId:correlation});return r.rows[0];});}
  catch(e:any){await this.storage.remove(objectKey);if(e.code==='23505'){const found=await this.db.queryOne<any>('SELECT * FROM import_jobs WHERE project_id=$1 AND idempotency_key=$2',[p,key]);if(found?.input_hash===hash)return this.publicJob(found);}throw e;}
  if(asyncMode){await this.db.transaction(async c=>{await c.query(`INSERT INTO exchange_worker_jobs(org_id,project_id,kind,import_job_id,created_by,updated_by) VALUES($1,$2,'scan',$3,$4,$4)`,[ctx.orgId,p,job.id,ctx.userId]);await this.audit.write(c,ctx,{entityType:'import_job',entityId:job.id,action:'upload_accepted',diff:{format:dto.format,async:true},correlationId:correlation});});return this.getImport(ctx,p,job.id);}
  try{await this.storage.scan(objectKey);const fileInfo=await this.inspect(bytes,dto.format,metadata.timezone,dto.encoding,dto.delimiter);await this.db.query(`UPDATE import_jobs SET scan_state='clean',state='pending',result=$2 WHERE id=$1`,[job.id,JSON.stringify({file_info:fileInfo})]);}catch(e){await this.db.query(`UPDATE import_jobs SET scan_state='error',state='failed',result=$2 WHERE id=$1`,[job.id,JSON.stringify({code:e instanceof DomainError?e.code:'scan_unavailable'})]);if(e instanceof ExchangeParseError)throw new DomainError('import',e.code,e.message);throw e;}
  return this.getImport(ctx,p,job.id);
 }
 /** Scan-passed file inspection summary (headers/sheets/calendars/anchor candidates); shared by upload and scan retry. */
 private async inspect(bytes:Buffer,format:'csv'|'xlsx'|'csv-package'|'xml',timezone:string,encoding?:string,delimiter?:string){const tables=await readTables(bytes,{format,timezone,hoursPerDay:8,encoding:encoding as any,delimiter});const rows=tables.Tasks??[];return{headers:Object.keys(rows[0]??{}),row_count:rows.length,sheets:Object.keys(tables),calendars:(tables.Calendars??[]).map(r=>({code:r['Calendar Code'],name:r.Name})),anchor_candidates:rows.filter(r=>/^0(?:min|m|h|d)$/.test(r.Duration??'')).map(r=>({key:r.GUID?'guid:'+r.GUID.toLowerCase():'uid:'+r['Unique ID'],name:r['Task Name']??'',wbs:r.WBS??''}))};}
 async listImports(ctx:UserContext,p:string,offset=0,limit=20){await this.project(this.connection(),ctx,p);const rows=await this.db.query<any>('SELECT * FROM import_jobs WHERE project_id=$1 AND org_id=$2 AND archived_at IS NULL ORDER BY created_at DESC,id DESC OFFSET $3 LIMIT $4',[p,ctx.orgId,offset,limit+1]);return{items:rows.slice(0,limit).map((j:any)=>this.publicJob(j)),next_offset:rows.length>limit?offset+limit:null};}
 async listExports(ctx:UserContext,p:string,offset=0,limit=20){await this.project(this.connection(),ctx,p);const rows=await this.db.query<any>('SELECT * FROM export_jobs WHERE project_id=$1 AND org_id=$2 AND archived_at IS NULL ORDER BY created_at DESC,id DESC OFFSET $3 LIMIT $4',[p,ctx.orgId,offset,limit+1]);return{items:rows.slice(0,limit).map((j:any)=>({id:j.id,state:j.state,format:j.format,report:j.filters?.report??null,created_at:j.created_at,expires_at:j.expires_at})),next_offset:rows.length>limit?offset+limit:null};}
 async cancel(ctx:UserContext,p:string,j:string,version:number,correlation:string){await this.job(this.connection(),ctx,p,j);return this.db.transaction(async c=>{await this.project(c,ctx,p,true);const job=await this.job(c,ctx,p,j,true);if(job.state==='cancelled')return this.publicJob(job);if(job.state==='succeeded'||job.state==='failed')throw DomainError.conflict('job_not_cancellable','已完成或失敗的匯入不可取消');if(Number(job.version)!==version)throw DomainError.conflict('version_conflict','作業版本已變更');const done=await c.query(`UPDATE import_jobs SET state='cancelled',updated_by=$2 WHERE id=$1 RETURNING *`,[j,ctx.userId]);await c.query(`UPDATE exchange_worker_jobs SET state='cancelled',lease_until=null,updated_by=$2 WHERE import_job_id=$1 AND state IN('pending','failed')`,[j,ctx.userId]);await this.storage.remove(job.object_key);await this.audit.write(c,ctx,{entityType:'import_job',entityId:j,action:'cancel',diff:{from:job.state},correlationId:correlation});return this.publicJob(done.rows[0]);});}
 async scanRetry(ctx:UserContext,p:string,j:string,version:number,correlation:string){
  const job=await this.job(this.connection(),ctx,p,j);if(job.state==='cancelled')throw DomainError.conflict('job_cancelled','作業已取消');if(job.scan_state!=='error')throw DomainError.conflict('scan_not_retryable','僅掃描不可用的作業可重試掃描');if(Number(job.version)!==version)throw DomainError.conflict('version_conflict','作業版本已變更');if(new Date(job.expires_at)<new Date())throw DomainError.conflict('job_expired','原檔已過期');const bytes=await this.storage.read(job.object_key);
  try{await this.storage.scan(job.object_key);const fileInfo=await this.inspect(bytes,job.source_type,job.timezone,job.request_metadata.encoding,job.request_metadata.delimiter);await this.db.query(`UPDATE import_jobs SET scan_state='clean',state='pending',result=$2,updated_by=$3 WHERE id=$1 AND version=$4`,[j,JSON.stringify({file_info:fileInfo}),ctx.userId,version]);await this.db.transaction(async c=>{await this.audit.write(c,ctx,{entityType:'import_job',entityId:j,action:'scan_retry',diff:{scan_state:'clean'},correlationId:correlation});});}
  catch(e){await this.db.query(`UPDATE import_jobs SET scan_state='error',state='failed',result=$2,updated_by=$3 WHERE id=$1`,[j,JSON.stringify({code:e instanceof DomainError?e.code:'scan_unavailable'}),ctx.userId]);if(e instanceof ExchangeParseError)throw new DomainError('import',e.code,e.message);throw e;}
  return this.getImport(ctx,p,j);
 }
 /** Retention sweep (Admin maintenance): purge expired original/output files and delete expired immutable previews.
  * Job rows and audit are retained as cleanup evidence. File removal marks purged_at only on success, so a failed
  * delete is retried on the next sweep. Preview deletion runs under a transaction-local privilege flag that the
  * immutable-preview trigger honours; ordinary users and paths can still never UPDATE or DELETE a preview. */
 async retentionSweep(ctx:UserContext,correlation:string){
  const importFiles=await this.db.query<any>(`SELECT id,object_key FROM import_jobs WHERE org_id=$1 AND purged_at IS NULL AND object_key IS NOT NULL AND expires_at<now()`,[ctx.orgId]);
  const purgedImports:string[]=[];for(const j of importFiles){try{await this.storage.purge(j.object_key);purgedImports.push(j.id);}catch{/* leave purged_at null for retry on the next sweep */}}
  if(purgedImports.length)await this.db.query(`UPDATE import_jobs SET purged_at=now(),updated_by=$2 WHERE id=ANY($1::uuid[])`,[purgedImports,ctx.userId]);
  const exportFiles=await this.db.query<any>(`SELECT id,output_key FROM export_jobs WHERE org_id=$1 AND purged_at IS NULL AND output_key IS NOT NULL AND expires_at<now()`,[ctx.orgId]);
  const purgedExports:string[]=[];for(const j of exportFiles){try{await this.storage.purge(j.output_key);purgedExports.push(j.id);}catch{/* retry next sweep */}}
  if(purgedExports.length)await this.db.query(`UPDATE export_jobs SET purged_at=now(),updated_by=$2 WHERE id=ANY($1::uuid[])`,[purgedExports,ctx.userId]);
  const previews=await this.db.transaction(async c=>{await c.query(`SET LOCAL app.retention_sweep='on'`);const d=await c.query(`DELETE FROM import_preview_versions WHERE org_id=$1 AND expires_at<now() RETURNING id`,[ctx.orgId]);return d.rows.map((r:any)=>r.id);});
  const summary={previews_deleted:previews.length,import_files_purged:purgedImports.length,export_files_purged:purgedExports.length,import_files_failed:importFiles.length-purgedImports.length,export_files_failed:exportFiles.length-purgedExports.length};
  await this.db.transaction(async c=>{await this.audit.write(c,ctx,{entityType:'exchange_retention',action:'retention_sweep',diff:summary,correlationId:correlation});});
  return summary;
 }
 // ===== Asynchronous worker (opt-in 202 path): scan imports and render exports in the background. =====
 private workerPermanent(e:unknown){return e instanceof ExchangeParseError||(e instanceof DomainError&&e.category!=='infrastructure');}
 private skip(){const e:any=new Error('worker job obsolete (cancelled or gone)');e.__skip=true;return e;}
 /** Claim a batch (lease-based, reclaiming expired running jobs) and run scan/render. Idempotent, retried with backoff, dead-lettered. */
 async processWorker(limit=10){
  const lease=Number(process.env.EXCHANGE_WORKER_LEASE_SEC??60),max=Number(process.env.EXCHANGE_WORKER_MAX_ATTEMPTS??3);
  const claimed=await this.db.query<any>(`UPDATE exchange_worker_jobs SET state='running',attempts=attempts+1,lease_until=now()+($2||' seconds')::interval WHERE id IN (SELECT id FROM exchange_worker_jobs WHERE ((state IN ('pending','failed') AND available_at<=now()) OR (state='running' AND lease_until<now())) ORDER BY available_at FOR UPDATE SKIP LOCKED LIMIT $1) RETURNING *`,[limit,String(lease)]);
  const results:any[]=[];
  for(const job of claimed){
   try{
    if(job.kind==='scan')await this.runScanJob(job);else await this.runRenderJob(job);
    await this.db.query(`UPDATE exchange_worker_jobs SET state='succeeded',lease_until=null,last_error=null WHERE id=$1`,[job.id]);
    results.push({id:job.id,kind:job.kind,target:job.import_job_id??job.export_job_id,state:'succeeded'});
   }catch(e:any){
    if(e?.__skip){await this.db.query(`UPDATE exchange_worker_jobs SET state='cancelled',lease_until=null WHERE id=$1`,[job.id]);results.push({id:job.id,kind:job.kind,state:'cancelled'});continue;}
    results.push(await this.workerFail(job,e,max));
   }
  }
  return{claimed:claimed.length,results};
 }
 private async workerFail(job:any,err:any,max:number){
  const attempts=job.attempts,message=err instanceof Error?err.message:String(err),terminal=this.workerPermanent(err)||attempts>=max;
  if(terminal){
   if(job.kind==='scan')await this.db.query(`UPDATE import_jobs SET scan_state=CASE WHEN scan_state='pending' THEN 'error' ELSE scan_state END,state=CASE WHEN state='pending' THEN 'failed' ELSE state END WHERE id=$1 AND state NOT IN('cancelled','succeeded')`,[job.import_job_id]);
   else await this.db.query(`UPDATE export_jobs SET state='failed' WHERE id=$1 AND state='pending'`,[job.export_job_id]);
   await this.db.query(`UPDATE exchange_worker_jobs SET state='dead',lease_until=null,last_error=$2 WHERE id=$1`,[job.id,message]);
   return{id:job.id,kind:job.kind,state:'dead',attempts,error:message};
  }
  const backoff=Number(process.env.EXCHANGE_WORKER_BACKOFF_SEC??30)*Math.pow(2,attempts-1);
  await this.db.query(`UPDATE exchange_worker_jobs SET state='failed',lease_until=null,last_error=$2,available_at=now()+($3||' seconds')::interval WHERE id=$1`,[job.id,message,String(backoff)]);
  return{id:job.id,kind:job.kind,state:'failed',attempts,error:message};
 }
 private async runScanJob(job:any){
  const imp=await this.db.queryOne<any>('SELECT * FROM import_jobs WHERE id=$1',[job.import_job_id]);
  if(!imp||imp.state==='cancelled')throw this.skip();
  if(imp.scan_state!=='pending')return; // already scanned or terminal → idempotent success
  const bytes=await this.storage.read(imp.object_key);
  try{await this.storage.scan(imp.object_key);const fileInfo=await this.inspect(bytes,imp.source_type,imp.timezone,imp.request_metadata.encoding,imp.request_metadata.delimiter);
   await this.db.transaction(async c=>{const cur=(await c.query('SELECT state,scan_state FROM import_jobs WHERE id=$1 FOR UPDATE',[imp.id])).rows[0];if(!cur||cur.state==='cancelled'||cur.scan_state!=='pending')return;await c.query(`UPDATE import_jobs SET scan_state='clean',state='pending',result=$2 WHERE id=$1`,[imp.id,JSON.stringify({file_info:fileInfo})]);await this.audit.write(c,{orgId:imp.org_id,userId:imp.created_by,roles:['Admin']} as UserContext,{entityType:'import_job',entityId:imp.id,action:'scan_clean',diff:{async:true},correlationId:'worker'});});
  }catch(e){
   if(this.workerPermanent(e)){const scanState=(e instanceof DomainError&&e.code==='file_infected')?'infected':'error';await this.db.query(`UPDATE import_jobs SET scan_state=$2,state='failed' WHERE id=$1 AND state NOT IN('cancelled','succeeded')`,[imp.id,scanState]);}
   throw e;
  }
 }
 private async runRenderJob(job:any){
  const exp=await this.db.queryOne<any>('SELECT * FROM export_jobs WHERE id=$1',[job.export_job_id]);
  if(!exp)throw this.skip();
  if(exp.state!=='pending')return; // already rendered or terminal → idempotent success
  const wctx={orgId:exp.org_id,userId:exp.created_by,roles:['Admin']} as UserContext;
  const dto:any={format:exp.format,...(exp.filters?.baselineId?{baselineId:exp.filters.baselineId}:{})};
  const generated=await this.generateExport(wctx,exp.project_id,dto);const output=await this.storage.write(generated.bytes);
  const committed=await this.db.transaction(async c=>{const cur=(await c.query('SELECT state FROM export_jobs WHERE id=$1 FOR UPDATE',[exp.id])).rows[0];if(!cur||cur.state!=='pending')return false;await c.query(`UPDATE export_jobs SET state='succeeded',output_key=$2,filters=$3 WHERE id=$1`,[exp.id,output,JSON.stringify({...exp.filters,report:generated.report,source_snapshot:generated.sourceSnapshot,output_hash:contentHash(generated.bytes)})]);await this.audit.write(c,wctx,{entityType:'export_job',entityId:exp.id,action:'export_rendered',diff:{format:exp.format,async:true},correlationId:'worker'});return true;});
  if(!committed)await this.storage.remove(output);
 }
 private publicJob(j:any){return{id:j.id,project_id:j.project_id,format:j.source_type,state:j.state,scan_state:j.scan_state,version:Number(j.version),result:j.result,status_url:`/projects/${j.project_id}/imports/${j.id}`,created_at:j.created_at,expires_at:j.expires_at};}
 private publicExport(j:any){return{id:j.id,project_id:j.project_id,state:j.state,format:j.format,report:j.filters?.report??null,status_url:`/projects/${j.project_id}/exports/${j.id}`,expires_at:j.expires_at};}
 async getImport(ctx:UserContext,p:string,j:string){return this.publicJob(await this.job(this.connection(),ctx,p,j));}
 async options(ctx:UserContext,p:string){await this.project(this.connection(),ctx,p);return{anchors:await this.db.query("SELECT id,name FROM project_tasks WHERE project_id=$1 AND type='anchor' AND archived_at IS NULL",[p]),resources:await this.db.query('SELECT id,code,name FROM resources WHERE org_id=$1 AND archived_at IS NULL ORDER BY name',[ctx.orgId]),calendars:await this.db.query('SELECT id,name,hours_per_day,timezone FROM calendars WHERE org_id=$1 AND archived_at IS NULL',[ctx.orgId])};}
 async preview(ctx:UserContext,p:string,j:string,dto:PreviewDto,version:number,correlation:string){
  const job=await this.job(this.connection(),ctx,p,j);if(Number(job.version)!==version)throw DomainError.conflict('version_conflict','匯入作業版本已變動');if(job.scan_state!=='clean'||job.state!=='pending')throw DomainError.conflict('job_not_ready','僅未提交且掃描通過的作業可預覽');if(new Date(job.expires_at)<new Date())throw DomainError.conflict('job_expired','原檔已過期');const bytes=await this.storage.read(job.object_key);
  return this.db.transaction(async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');const current=await this.job(c,ctx,p,j,true);if(Number(current.version)!==version)throw DomainError.conflict('version_conflict','作業版本變動');const project=await this.project(c,ctx,p);const calendars=(await c.query('SELECT * FROM calendars WHERE org_id=$1 AND archived_at IS NULL',[ctx.orgId])).rows;const defaultCal=calendars.find(v=>v.id===project.default_calendar_id);if(!defaultCal)throw DomainError.validation('案件缺少有效預設日曆');
   const calendarHours:Record<string,number>={};for(const cal of calendars){calendarHours[cal.id]=Number(cal.hours_per_day);calendarHours[cal.name]=Number(cal.hours_per_day);}for(const [code,id]of Object.entries(dto.calendarMap??{})){const cal=calendars.find(v=>v.id===id);if(!cal)throw DomainError.validation('日曆映射不在本組織');calendarHours[code]=Number(cal.hours_per_day);}
   const parseOptions:ParseOptions={format:job.source_type,encoding:job.request_metadata.encoding,timezone:job.timezone,hoursPerDay:Number(defaultCal.hours_per_day),calendarHours,mapping:dto.mapping,dateFormat:dto.dateFormat,startTime:dto.startTime,finishTime:dto.finishTime,delimiter:dto.delimiter,predecessorMode:dto.predecessorMode};
   let parsed:ParsedExchange;try{parsed=await parseExchange(bytes,parseOptions);}catch(e){if(e instanceof ExchangeParseError)throw new DomainError('import',e.code,e.message);throw e;}
   const payload=await this.prepare(c,ctx,project,parsed,dto,parseOptions,calendars);const vector=await this.vector(c,ctx.orgId,p,payload.scope);const payloadHash=stableHash(payload);const r=await c.query(`INSERT INTO import_preview_versions(org_id,project_id,import_job_id,sequence_no,parser_version,payload,payload_hash,vector_hash,decision_hash,errors,warnings,created_by) SELECT $1,$2,$3,COALESCE(max(sequence_no),0)+1,$4,$5,$6,$7,$8,$9,$10,$11 FROM import_preview_versions WHERE import_job_id=$3 RETURNING id,sequence_no,payload_hash,vector_hash`,[ctx.orgId,p,j,PARSER_VERSION,JSON.stringify(payload),payloadHash,vector,stableHash(dto),JSON.stringify(payload.issues.filter((x:Issue)=>x.severity==='error')),JSON.stringify(payload.issues.filter((x:Issue)=>x.severity==='warning')),ctx.userId]);await c.query(`UPDATE import_jobs SET mapping=$2,result=COALESCE(result,'{}'::jsonb)||$3::jsonb,updated_by=$4 WHERE id=$1`,[j,JSON.stringify(dto),JSON.stringify({preview_id:r.rows[0].id}),ctx.userId]);await this.audit.write(c,ctx,{entityType:'import_job',entityId:j,action:'preview',diff:{preview_id:r.rows[0].id,errors:payload.issues.filter((x:Issue)=>x.severity==='error').length,payload_hash:payloadHash},correlationId:correlation});const v=(await c.query('SELECT version FROM import_jobs WHERE id=$1',[j])).rows[0].version;return{...r.rows[0],job_version:Number(v),issues:payload.issues,changes:payload.tasks.map((t:any)=>({key:t.key,id:t.id,name:t.name,action:t.existing?'update':'create',work:t.work,resources:t.resources})),profiles:payload.profiles,task_count:payload.tasks.length,can_commit:!payload.issues.some((x:Issue)=>x.severity==='error')};
  });
 }
 private async prepare(c:Queryable,ctx:UserContext,project:any,parsed:ParsedExchange,dto:PreviewDto,opts:ParseOptions,calendars:any[]){
  const issues=[...parsed.issues];const existing=(await c.query('SELECT * FROM project_tasks WHERE project_id=$1 AND org_id=$2 AND archived_at IS NULL',[project.id,ctx.orgId])).rows;const external=(await c.query('SELECT * FROM external_id_map WHERE project_id=$1 AND org_id=$2 AND entity_type=\'task\'',[project.id,ctx.orgId])).rows;const oldEdges=(await c.query('SELECT * FROM task_dependencies WHERE project_id=$1 AND archived_at IS NULL',[project.id])).rows;const resources=(await c.query('SELECT * FROM resources WHERE org_id=$1 AND archived_at IS NULL',[ctx.orgId])).rows;const aliases=(await c.query('SELECT * FROM resource_aliases WHERE org_id=$1 AND archived_at IS NULL',[ctx.orgId])).rows;const disciplines=(await c.query('SELECT id,code FROM disciplines')).rows;
  const tasks=parsed.tasks.map(t=>{const matches=external.filter(e=>(t.guid&&e.system==='msproject-guid'&&e.external_id===t.guid.toLowerCase())||(t.uid&&e.system==='msproject-uid'&&e.external_id===t.uid));const ids=new Set(matches.map(e=>e.entity_id));if(ids.size>1)addIssue(issues,'GUID','identity_conflict','GUID與UID指向不同工作',t.row);const old=existing.find(e=>ids.has(e.id));if(old&&dto.mode!=='upsert')addIssue(issues,'Unique ID','duplicate_external_id','已存在工作，須明確選upsert',t.row);if(old?.locked)addIssue(issues,'Unique ID','task_locked','鎖定工作不可改寫',t.row);if(existing.some(e=>e.wbs_code===t.wbs&&e.id!==old?.id))addIssue(issues,'WBS','duplicate_wbs','已有相同WBS但無外部身分對照',t.row);
   if(old?.actual_start&&t.actualStart&&toMinute(old.actual_start)!==toMinute(t.actualStart)||old?.actual_finish&&t.actualFinish&&toMinute(old.actual_finish)!==toMinute(t.actualFinish))addIssue(issues,'Actual Finish','actual_locked','既有實績不可由匯入改寫',t.row);
   if(old){const fields:Record<string,[string,any]>={Start:['start',old.planned_start?new Date(old.planned_start).toISOString():null],Finish:['finish',old.planned_finish?new Date(old.planned_finish).toISOString():null],Notes:['notes',old.notes??''],'% Complete':['percent',Number(old.percent_complete)],'Remaining Duration':['remaining',old.remaining_minutes],'Constraint Type':['constraint',old.constraint_type],'Constraint Date':['constraintDate',old.constraint_date?new Date(old.constraint_date).toISOString():null],Milestone:['milestone',old.milestone],Summary:['summary',old.summary]};for(const [column,[field,value]]of Object.entries(fields))if(!t.supplied.includes(column))(t as any)[field]=value;}
   const calendarId=t.calendar?(dto.calendarMap?.[t.calendar]??calendars.find(v=>v.id===t.calendar||v.name===t.calendar)?.id):old?.calendar_id??project.default_calendar_id;const disciplineId=t.discipline?disciplines.find(d=>d.code===t.discipline)?.id:old?.discipline_id??null;if(!calendarId)addIssue(issues,'Calendar Code','calendar_unknown','須映射本組織有效日曆',t.row);if(t.discipline&&!disciplineId)addIssue(issues,'System Code','discipline_unknown','系統代碼不存在',t.row);
   return{...t,id:old?.id??randomUUID(),existing:!!old,replaceDependencies:t.supplied.includes('Predecessors'),replaceAssignments:t.supplied.includes('Work')||t.supplied.includes('Resource Names')||!!parsed.sheets.Assignments?.length,calendarId,disciplineId,actualStart:old?.actual_start?new Date(old.actual_start).toISOString():t.actualStart,actualFinish:old?.actual_finish?new Date(old.actual_finish).toISOString():t.actualFinish,percent:old?.actual_finish?100:t.percent};});
  const byKey=new Map(tasks.map(t=>[t.key,t]));const dependencyRows=parsed.dependencies.map(e=>({...e,predecessor_task_id:byKey.get(e.from)!.id,successor_task_id:byKey.get(e.to)!.id,lag_minutes:e.lag}));
  const newResources:any[]=[];for(const name of dto.createResources??[]){if(!ctx.roles.includes('Admin')){addIssue(issues,'Resource Names','resource_create_forbidden','建立組織資源需Admin');continue;}if(!name.trim()||name.length>200||resources.some(r=>r.name===name)){addIssue(issues,'Resource Names','resource_create_invalid','資源名稱空白、超限或已存在');continue;}const r={id:randomUUID(),code:'MSP-'+randomUUID(),name,created:true};newResources.push(r);resources.push(r);}
  const resolveResource=(name:string,row:number)=>{const sourceDefinition=(parsed.sheets.Resources??[]).find(r=>r['Resource Code']===name||r['Resource GUID']===name);const sourceName=sourceDefinition?.Name??name;const explicit=dto.resourceMap?.[name]??dto.resourceMap?.[sourceName];const matches=explicit?resources.filter(r=>r.id===explicit):resources.filter(r=>r.code===name||r.id===name);const exact=matches.length?matches:resources.filter(r=>r.name===sourceName);const candidates=exact.length?exact:resources.filter(r=>aliases.some(a=>a.resource_id===r.id&&a.alias.toLowerCase()===name.toLowerCase()));if(candidates.length!==1){addIssue(issues,'Resource Names',candidates.length?'resource_ambiguous':'resource_unknown','資源 '+name+'：請選定本組織資源或明確建立',row);return null;}return candidates[0];};
  const assignments:any[]=[];const assignmentSheets=parsed.sheets.Assignments??[];const assignedTasks=new Set<string>();
  for(let i=0;i<assignmentSheets.length;i++){const r=assignmentSheets[i];try{const t=tasks.find(t=>t.guid&&t.guid.toLowerCase()===r['Task GUID']?.toLowerCase()||t.uid&&t.uid===r['Task UID']);if(!t||t.summary)throw new Error('指派工作識別不明或為摘要');const resource=resolveResource(r['Resource Code']||r['Resource GUID']||r['Resource Name']||'',i+2);if(!resource)continue;const units=Number(r.Units);if(!r.Units||!Number.isFinite(units)||units<0||units>99.9999)throw new Error('Units需明示有效投入比例');const work=durationMinutes(r['Planned Work'],opts.hoursPerDay);const start=parseInstant(r.Start,opts),finish=parseInstant(r.Finish,opts,'finish');if(!start||!finish||finish<start)throw new Error('指派日期需成對有效');let contour=null;if(r.Contour){contour=JSON.parse(r.Contour);if(!Array.isArray(contour)||contour.some((v:any)=>!v||!Number.isSafeInteger(v.work_minutes)||v.work_minutes<0||!v.start||!v.finish||Date.parse(v.start)<Date.parse(start)||Date.parse(v.finish)>Date.parse(finish)||Date.parse(v.finish)<Date.parse(v.start)))throw new Error('Contour無效');let last=-Infinity;for(const segment of contour){const begin=Date.parse(segment.start),end=Date.parse(segment.finish);if(!Number.isFinite(begin)||!Number.isFinite(end)||begin<last)throw new Error('Contour順序或日期無效');last=end;}if(contour.reduce((n:number,v:any)=>n+v.work_minutes,0)!==work)throw new Error('Contour總Work不符');}if(r['Booking Type']&&!['committed','proposed','cover'].includes(r['Booking Type']))throw new Error('Booking Type須為committed/proposed/cover');if(assignments.some(a=>a.taskId===t.id&&a.resourceId===resource.id&&a.start===start&&a.booking===(r['Booking Type']||'committed')))throw new Error('指派身分重複');assignments.push({taskId:t.id,resourceId:resource.id,units,work,actual:r['Actual Work']?durationMinutes(r['Actual Work'],opts.hoursPerDay):0,remaining:r['Remaining Work']?durationMinutes(r['Remaining Work'],opts.hoursPerDay):null,start,finish,booking:r['Booking Type']||'committed',contour});assignedTasks.add(t.id);}catch(e){addIssue(issues,'Assignments','assignment_invalid',e instanceof Error?e.message:'指派錯誤',i+2);}}
  for(const t of tasks){if(t.summary)continue;if(assignedTasks.has(t.id)){if(assignments.filter(a=>a.taskId===t.id).reduce((n,a)=>n+a.work,0)!==t.work)addIssue(issues,'Work','work_mismatch','指派工時總和不等於Task Work',t.row);continue;}if(!t.resources.length)continue;const allocation=dto.workAllocations?.[t.key];if(!allocation&&t.resources.length>1){addIssue(issues,'Work','work_allocation_required','多人Work須明確分配，建議等分但不自動提交',t.row);continue;}let total=0;for(const name of t.resources){const resource=resolveResource(name,t.row);if(!resource)continue;const work=t.resources.length===1?t.work:allocation?.[name];if(work===undefined||!Number.isSafeInteger(work)||work<0){addIssue(issues,'Work','work_allocation_invalid','分配需為非負整分鐘',t.row);continue;}total+=work;const hasUnits=Object.hasOwn(dto.units??{},name);const units=hasUnits?dto.units![name]:1;if(!hasUnits)addIssue(issues,'Units','units_assumed','未提供Units，建議1.0；須確認警告',t.row,'warning');if(!Number.isFinite(units)||units<0||units>99.9999)addIssue(issues,'Units','units_invalid','Units無效',t.row);if(!t.start||!t.finish)addIssue(issues,'Start','assignment_dates_missing','有指派工作需起訖日期',t.row);assignments.push({taskId:t.id,resourceId:resource.id,units,work,actual:0,remaining:null,start:t.start,finish:t.finish,booking:'committed',contour:null});}if(total!==t.work)addIssue(issues,'Work','work_mismatch','分配總和需等於來源Work',t.row);}
  const usedResources=new Set(assignments.map(a=>a.resourceId));
  for(const [index,row]of(parsed.sheets.Resources??[]).entries()){const resource=resources.find(r=>usedResources.has(r.id)&&(r.id===(dto.resourceMap?.[row['Resource Code']]??dto.resourceMap?.[row.Name])||r.code===row['Resource Code']||r.name===row.Name));if(!resource)continue;if(row['Max Units']){const units=Number(row['Max Units']);if(!Number.isFinite(units)||units<0||units>99.9999)addIssue(issues,'Resources','resource_profile_invalid','Max Units無效',index+2);else if(units!==Number(resource.max_units??1))addIssue(issues,'Resources','resource_capacity_difference','來源Max Units與組織資源不同；匯入保留組織設定，需確認容量差異',index+2,'warning');}}
  for(const [index,row]of(parsed.sheets.Calendars??[]).entries()){const calendar=calendars.find(v=>v.id===(dto.calendarMap?.[row['Calendar Code']]??row['Calendar Code'])||v.name===row.Name);if(calendar&&row.Timezone&&calendar.timezone!==row.Timezone)addIssue(issues,'Calendars','calendar_timezone_difference','來源與目標日曆時區不同；日期保留UTC、容量使用目標設定，須確認',index+2,'warning');}
  const baselineAssignments:any[]=[];const baselineSeen=new Set<string>();
  for(const [index,row]of(parsed.sheets.Baselines??[]).entries()){try{
   const t=tasks.find(t=>t.guid?.toLowerCase()===row['Task GUID']?.toLowerCase());if(!t)throw new Error('基準工作GUID不存在');const start=parseInstant(row.Start,opts),finish=parseInstant(row.Finish,opts,'finish');if(!start||!finish||finish<start)throw new Error('基準日期無效');const work=durationMinutes(row.Work,opts.hoursPerDay);
   if(row.Kind==='task'){const key='task:'+t.id;if(baselineSeen.has(key))throw new Error('基準工作重複');baselineSeen.add(key);if(t.baselineStart&&t.baselineStart!==start||t.baselineFinish&&t.baselineFinish!==finish)throw new Error('Tasks與Baselines日期矛盾');t.baselineStart=start;t.baselineFinish=finish;(t as any).baselineDuration=durationMinutes(row.Duration,opts.hoursPerDay);(t as any).baselineWork=work;}
   else if(row.Kind==='assignment'){const resource=resolveResource(row['Resource Code']||row['Resource GUID']||'',index+2);if(!resource)continue;const key=t.id+':'+resource.id;if(baselineSeen.has(key))throw new Error('基準指派重複');baselineSeen.add(key);const units=Number(row.Units);if(!row.Units||!Number.isFinite(units)||units<0||units>99.9999)throw new Error('基準Units無效');baselineAssignments.push({taskId:t.id,resourceId:resource.id,work,units,start,finish});}
   else throw new Error('基準Kind須為task或assignment');
  }catch(e){addIssue(issues,'Baselines','baseline_invalid',e instanceof Error?e.message:'基準無效',index+2);}}
  for(const a of baselineAssignments)if(!tasks.find(t=>t.id===a.taskId)?.baselineStart)addIssue(issues,'Baselines','baseline_task_missing','基準指派缺少基準工作');
  if(assignments.length>LIMITS.assignments)addIssue(issues,'Assignments','assignment_limit','指派数超限');
  const importedAnchor=dto.anchorKey?byKey.get(dto.anchorKey):undefined;const oldAnchor=existing.find(t=>t.type==='anchor'&&(!dto.anchorTaskId||t.id===dto.anchorTaskId));const anchorId=importedAnchor?.id??oldAnchor?.id;if(!anchorId)addIssue(issues,'Anchor','anchor_required','請明確指定匯入錨點，或確認現有錨點');if(!importedAnchor&&oldAnchor&&!dto.anchorTaskId)addIssue(issues,'Anchor','anchor_confirmation_required','須明確確認既有錨點UUID');if(importedAnchor&&(!importedAnchor.milestone||importedAnchor.summary||importedAnchor.duration!==0))addIssue(issues,'Anchor','anchor_invalid','掛件錨點須為零工期里程碑');
  const filing=project.permit_filing_date?DateTime.fromISO(project.permit_filing_date+'T18:00',{zone:project.timezone}).toUTC():null;if(!filing?.isValid)addIssue(issues,'Anchor','filing_missing','案件缺有效掛件日');if(importedAnchor?.start&&toMinute(importedAnchor.start)!==Math.floor(filing!.toMillis()/60000))addIssue(issues,'Anchor','anchor_conflict','錨點日期與案件掛件日不一致',importedAnchor.row);
  for(const t of [...tasks].reverse()){const children=tasks.filter(v=>v.parentKey===t.key);if(t.summary&&children.length){t.start=children.map(v=>v.start).filter(Boolean).sort()[0]??null;t.finish=children.map(v=>v.finish).filter(Boolean).sort().at(-1)??null;}if(t.id!==anchorId&&t.finish&&!t.actualFinish&&filing&&toMinute(t.finish)!>Math.floor(filing.toMillis()/60000))addIssue(issues,'Finish','anchor_conflict','未完成計畫超過掛件',t.row);}
  if(!issues.some(x=>x.severity==='error')&&filing&&anchorId){
   const allTasks:Task[]=existing.filter(t=>!tasks.some(v=>v.id===t.id)).map(t=>({...buildTask(t,project.default_calendar_id),remainingMinutes:t.remaining_minutes??undefined}));for(const t of tasks)allTasks.push({id:t.id,type:t.id===anchorId?'anchor':t.summary?'summary':t.milestone?'milestone':'task',durationMinutes:t.duration,calendarId:t.calendarId,constraint:{type:t.constraint as any,date:toMinute(t.constraintDate)},actualStart:toMinute(t.actualStart),actualFinish:toMinute(t.actualFinish),remainingMinutes:t.remaining??undefined});
   const allEdges:Dependency[]=oldEdges.filter(e=>!tasks.some(t=>t.id===e.successor_task_id&&t.replaceDependencies)).map(buildDependency);allEdges.push(...dependencyRows.map(e=>({predecessorId:e.predecessor_task_id,successorId:e.successor_task_id,relation:e.relation,lagMinutes:e.lag})));
   const requested=[...new Set(allTasks.map(t=>t.calendarId))];const needed=new Set(requested);for(const id of [...needed]){let meta=calendars.find(v=>v.id===id);const seen=new Set<string>();while(meta?.parent_calendar_id&&!seen.has(meta.id)){seen.add(meta.id);needed.add(meta.parent_calendar_id);meta=calendars.find(v=>v.id===meta.parent_calendar_id);}}
   const workingDays=(await c.query('SELECT * FROM calendar_working_days WHERE calendar_id=ANY($1::uuid[]) AND archived_at IS NULL',[[...needed]])).rows;const exceptions=(await c.query('SELECT * FROM calendar_exceptions WHERE calendar_id=ANY($1::uuid[]) AND archived_at IS NULL',[[...needed]])).rows;
   let calInput:Calendar[]=[];try{calInput=resolveCalendars(calendars,workingDays,exceptions,requested);}catch(e){if(e instanceof ExchangeParseError)addIssue(issues,'Calendar Code',e.code,e.message);else throw e;}
   for(const t of tasks){if(t.summary||t.actualFinish||!t.start||!t.finish)continue;const calendar=calInput.find(c=>c.id===t.calendarId);if(!calendar)continue;const start=toMinute(t.start)!,finish=toMinute(t.finish)!;if(t.duration>0&&(workingMinutesBetween(start,start+1,calendar)!==1||workingMinutesBetween(finish-1,finish,calendar)!==1))addIssue(issues,'Start','source_calendar_conflict','來源起訖不在有效工作時段邊界',t.row);if(workingMinutesBetween(start,finish,calendar)!==t.duration)addIssue(issues,'Duration','source_duration_conflict','來源工期與計畫期間工作分鐘不符；請修正工期或日曆',t.row);const date=toMinute(t.constraintDate);if(date!==undefined&&((t.constraint==='MSO'&&start!==date)||(t.constraint==='MFO'&&finish!==date)||(t.constraint==='SNET'&&start<date)||(t.constraint==='SNLT'&&start>date)||(t.constraint==='FNET'&&finish<date)||(t.constraint==='FNLT'&&finish>date)))addIssue(issues,'Constraint Date','source_constraint_conflict','來源計畫日期違反自身限制；不自動重排',t.row);}
   const result=issues.some(x=>x.severity==='error')?null:schedule({tasks:allTasks,calendars:calInput,dependencies:allEdges,anchor:{taskId:anchorId,instant:Math.floor(filing.toMillis()/60000)}});if(result&&!result.ok)addIssue(issues,'Schedule','scheduling_conflict',JSON.stringify(result.conflicts));
   for(const e of dependencyRows){const a=tasks.find(t=>t.id===e.predecessor_task_id),b=tasks.find(t=>t.id===e.successor_task_id);if(!a?.start||!a.finish||!b?.start||!b.finish)continue;const cal=calInput.find(c=>c.id===b.calendarId);if(!cal)continue;const at=toMinute(e.relation[0]==='F'?a.finish:a.start)!,bt=toMinute(e.relation[1]==='F'?b.finish:b.start)!;const bound=e.lag<0?subtractWorking(at,-e.lag,cal):addWorking(at,e.lag,cal);if(bt<bound)addIssue(issues,'Predecessors','source_dependency_conflict','來源計畫日期違反相依界限',e.row);}
  }
  if(issues.some(x=>x.severity==='warning')&&!dto.acknowledgeWarnings)addIssue(issues,'Warnings','warnings_unacknowledged','請確認警告再產生可提交預覽');
  const resourceIds=[...new Set([...assignments,...baselineAssignments].map(a=>a.resourceId))];const calendarSet=new Set<string>([project.default_calendar_id,...existing.map(t=>t.calendar_id),...tasks.map(t=>t.calendarId)].filter(Boolean));const profiles=(await c.query('SELECT calendar_id FROM resource_calendars WHERE resource_id=ANY($1::uuid[]) AND archived_at IS NULL',[resourceIds])).rows;for(const r of profiles)calendarSet.add(r.calendar_id);for(const id of [...calendarSet]){let cal=calendars.find(v=>v.id===id);const seen=new Set<string>();while(cal?.parent_calendar_id&&!seen.has(cal.id)){seen.add(cal.id);calendarSet.add(cal.parent_calendar_id);cal=calendars.find(v=>v.id===cal.parent_calendar_id);}}
  // 來源日曆／資源 profile 與目標差異（供決策 UI 明示，不無聲修改組織設定）
  const calendarProfiles=(parsed.sheets.Calendars??[]).map(row=>{const code=row['Calendar Code'];const mappedId=dto.calendarMap?.[code];const target=calendars.find(v=>v.id===(mappedId??code)||v.name===row.Name);const differences:string[]=[];if(!target)differences.push('unmapped');else{if(row.Timezone&&target.timezone!==row.Timezone)differences.push('timezone');if(row['Hours Per Day']&&Number(row['Hours Per Day'])!==Number(target.hours_per_day))differences.push('hours');}return{code:code??'',name:row.Name??'',source_timezone:row.Timezone??'',source_hours:row['Hours Per Day']??'',target:target?{id:target.id,name:target.name,timezone:target.timezone,hours_per_day:Number(target.hours_per_day)}:null,differences};});
  const resourceProfiles=(parsed.sheets.Resources??[]).map(row=>{const code=row['Resource Code'],name=row.Name;const mappedId=dto.resourceMap?.[code]??dto.resourceMap?.[name];const target=resources.find(r=>r.id===mappedId||r.code===code||r.name===name);const differences:string[]=[];if(!target)differences.push('unmapped');else if(row['Max Units']&&Number.isFinite(Number(row['Max Units']))&&Number(row['Max Units'])!==Number(target.max_units??1))differences.push('capacity');return{code:code??'',name:name??'',source_max_units:row['Max Units']??'',source_type:row.Type??'',target:target?{id:target.id,name:target.name,max_units:Number(target.max_units??1)}:null,differences};});
  return{scope:{resourceIds,calendarIds:[...calendarSet].sort()},tasks,dependencies:dependencyRows,assignments,baselineAssignments,newResources,issues,anchorId,activateBaseline:!!dto.activateBaseline,mode:dto.mode??'create-only',profiles:{calendars:calendarProfiles,resources:resourceProfiles}};
 }
 async getPreview(ctx:UserContext,p:string,j:string,v:string,offset=0,limit=100){await this.job(this.connection(),ctx,p,j);const row=await this.db.queryOne<any>('SELECT * FROM import_preview_versions WHERE id=$1 AND import_job_id=$2 AND org_id=$3 AND project_id=$4',[v,j,ctx.orgId,p]);if(!row)throw DomainError.notFound('預覽');const tasks=row.payload.tasks;return{id:row.id,payload_hash:row.payload_hash,errors:row.errors,warnings:row.warnings,total:tasks.length,changes:tasks.slice(offset,offset+limit).map((t:any)=>({key:t.key,id:t.id,name:t.name,action:t.existing?'update':'create',planned_start:t.start,planned_finish:t.finish,work:t.work})),profiles:row.payload.profiles??{calendars:[],resources:[]},next_offset:offset+limit<tasks.length?offset+limit:null};}
 async commit(ctx:UserContext,p:string,j:string,dto:CommitDto,key:string|undefined,version:number,correlation:string){
  key=this.key(key);await this.job(this.connection(),ctx,p,j);try{return await this.db.transaction(async c=>{
   await c.query('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');await this.project(c,ctx,p,true);const job=await this.job(c,ctx,p,j,true);const requestHash=stableHash(dto);
   if(job.state==='succeeded'){if(job.result.commit_key===key&&job.result.commit_hash===requestHash)return this.publicJob(job);throw DomainError.conflict('idempotency_conflict','此匯入已提交，請使用原提交key及預覽');}
   if(job.state==='cancelled')throw DomainError.conflict('job_cancelled','作業已取消，請重新上傳');
   if(Number(job.version)!==version)throw DomainError.conflict('version_conflict','作業版本已變更');const r=await c.query('SELECT * FROM import_preview_versions WHERE id=$1 AND import_job_id=$2 AND org_id=$3 AND project_id=$4',[dto.previewId,j,ctx.orgId,p]);const preview=r.rows[0];if(!preview)throw DomainError.notFound('預覽');if(preview.payload_hash!==dto.previewHash||preview.payload_hash!==stableHash(preview.payload))throw DomainError.conflict('preview_hash','預覽雜湊不符');if(preview.parser_version!==PARSER_VERSION||new Date(preview.expires_at)<new Date()||preview.vector_hash!==await this.vector(c,ctx.orgId,p,preview.payload.scope))throw DomainError.conflict('preview_stale','資料已變動或預覽過期，請重新預覽');if(preview.errors.length)throw new DomainError('import','preview_invalid','預覽有錯誤不可提交');if(job.scan_state!=='clean')throw DomainError.conflict('scan_required','檔案未通過掃描');
   const data=preview.payload;
   for(const resource of data.newResources){await c.query('INSERT INTO resources(id,org_id,code,name,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$5)',[resource.id,ctx.orgId,resource.code,resource.name,ctx.userId]);await this.audit.write(c,ctx,{entityType:'resource',entityId:resource.id,action:'import_create',diff:{name:resource.name,job:j},correlationId:correlation});}
   for(let i=0;i<data.tasks.length;i++){
    const t=data.tasks[i],parent=data.tasks.find((v:any)=>v.key===t.parentKey)?.id??null;const type=t.id===data.anchorId?'anchor':t.summary?'summary':t.milestone?'milestone':'task';const assigned=data.assignments.some((a:any)=>a.taskId===t.id);const values=[t.id,ctx.orgId,p,parent,t.wbs,String(i).padStart(8,'0'),t.name,type,t.start,t.finish,t.actualStart,t.actualFinish,t.duration,t.percent,t.remaining,t.constraint,t.constraintDate,t.milestone,t.summary,t.notes,t.calendarId,t.disciplineId,!t.replaceAssignments&&t.existing?(await c.query('SELECT unassigned_work_minutes FROM project_tasks WHERE id=$1',[t.id])).rows[0].unassigned_work_minutes:assigned?0:t.work,ctx.userId];
    const before=t.existing?(await c.query('SELECT * FROM project_tasks WHERE id=$1 FOR UPDATE',[t.id])).rows[0]:null;if(before?.locked)throw DomainError.conflict('task_locked','工作已鎖定');
    if(!t.existing)await c.query(`INSERT INTO project_tasks(id,org_id,project_id,parent_task_id,wbs_code,sort_key,name,type,planned_start,planned_finish,actual_start,actual_finish,duration_minutes,percent_complete,remaining_minutes,constraint_type,constraint_date,milestone,summary,notes,calendar_id,discipline_id,unassigned_work_minutes,created_by,updated_by,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$24,CASE WHEN $14::numeric=100 THEN 'completed' WHEN $14::numeric>0 THEN 'in_progress' ELSE 'not_started' END)`,values);
    else await c.query(`UPDATE project_tasks SET parent_task_id=$4,wbs_code=$5,sort_key=$6,name=$7,type=$8,planned_start=$9,planned_finish=$10,actual_start=COALESCE(actual_start,$11),actual_finish=COALESCE(actual_finish,$12),duration_minutes=$13,percent_complete=$14,remaining_minutes=$15,constraint_type=$16,constraint_date=$17,milestone=$18,summary=$19,notes=$20,calendar_id=$21,discipline_id=$22,unassigned_work_minutes=$23,updated_by=$24,status=CASE WHEN $14::numeric=100 THEN 'completed' WHEN $14::numeric>0 THEN 'in_progress' ELSE 'not_started' END WHERE id=$1 AND org_id=$2 AND project_id=$3`,values);
    for(const [system,external]of [['msproject-guid',t.guid?.toLowerCase()],['msproject-uid',t.uid]])if(external)await c.query(`INSERT INTO external_id_map(org_id,project_id,system,external_id,entity_type,entity_id,created_by,updated_by) VALUES($1,$2,$3,$4,'task',$5,$6,$6) ON CONFLICT(project_id,system,entity_type,external_id) DO NOTHING`,[ctx.orgId,p,system,external,t.id,ctx.userId]);
    await this.audit.write(c,ctx,{entityType:'task',entityId:t.id,action:t.existing?'import_update':'import_create',diff:{job:j,before:before?{name:before.name,planned_start:before.planned_start,planned_finish:before.planned_finish,version:before.version}:null,after:{name:t.name,start:t.start,finish:t.finish}},correlationId:correlation});
   }
   const affected=data.tasks.filter((t:any)=>t.replaceDependencies).map((t:any)=>t.id);const oldDeps=(await c.query('SELECT id FROM task_dependencies WHERE successor_task_id=ANY($1::uuid[]) AND project_id=$2 AND archived_at IS NULL',[affected,p])).rows;
   await c.query('UPDATE task_dependencies SET archived_at=now(),updated_by=$3 WHERE successor_task_id=ANY($1::uuid[]) AND project_id=$2 AND archived_at IS NULL',[affected,p,ctx.userId]);
   for(const old of oldDeps)await this.audit.write(c,ctx,{entityType:'dependency',entityId:old.id,action:'import_archive',diff:{job:j},correlationId:correlation});
   for(const e of data.dependencies){const r=await c.query(`INSERT INTO task_dependencies(org_id,project_id,predecessor_task_id,successor_task_id,relation,lag_minutes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7) ON CONFLICT(predecessor_task_id,successor_task_id,relation) DO UPDATE SET lag_minutes=EXCLUDED.lag_minutes,archived_at=NULL,updated_by=EXCLUDED.updated_by RETURNING id`,[ctx.orgId,p,e.predecessor_task_id,e.successor_task_id,e.relation,e.lag,ctx.userId]);await this.audit.write(c,ctx,{entityType:'dependency',entityId:r.rows[0].id,action:'import_write',diff:{job:j,relation:e.relation,lag_minutes:e.lag},correlationId:correlation});}
   const assignmentAffected=data.tasks.filter((t:any)=>t.replaceAssignments).map((t:any)=>t.id);const oldAssign=(await c.query('SELECT id,actual_work_minutes FROM resource_assignments WHERE task_id=ANY($1::uuid[]) AND project_id=$2 AND archived_at IS NULL',[assignmentAffected,p])).rows;if(oldAssign.some(a=>a.actual_work_minutes>0))throw DomainError.conflict('assignment_actual_locked','工作已有指派實績，不可取代指派');
   await c.query('UPDATE resource_assignments SET archived_at=now(),updated_by=$3 WHERE task_id=ANY($1::uuid[]) AND project_id=$2 AND archived_at IS NULL',[assignmentAffected,p,ctx.userId]);for(const a of oldAssign)await this.audit.write(c,ctx,{entityType:'assignment',entityId:a.id,action:'import_archive',diff:{job:j},correlationId:correlation});
   for(const a of data.assignments){const r=await c.query(`INSERT INTO resource_assignments(org_id,project_id,task_id,resource_id,assignment_units,planned_work_minutes,actual_work_minutes,remaining_work_minutes,assignment_start,assignment_finish,booking_type,contour,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) ON CONFLICT(task_id,resource_id,booking_type,assignment_start) DO UPDATE SET assignment_units=EXCLUDED.assignment_units,planned_work_minutes=EXCLUDED.planned_work_minutes,actual_work_minutes=EXCLUDED.actual_work_minutes,remaining_work_minutes=EXCLUDED.remaining_work_minutes,assignment_finish=EXCLUDED.assignment_finish,contour=EXCLUDED.contour,archived_at=NULL,updated_by=EXCLUDED.updated_by RETURNING id`,[ctx.orgId,p,a.taskId,a.resourceId,a.units,a.work,a.actual,a.remaining,a.start,a.finish,a.booking,JSON.stringify(a.contour),ctx.userId]);await this.audit.write(c,ctx,{entityType:'assignment',entityId:r.rows[0].id,action:'import_write',diff:{job:j,work_minutes:a.work,units:a.units},correlationId:correlation});}
   let baselineId=null;const baselineTasks=data.tasks.filter((t:any)=>t.baselineStart);if(baselineTasks.length){if(data.activateBaseline)await c.query(`UPDATE baselines SET status='superseded',updated_by=$2 WHERE project_id=$1 AND status='active'`,[p,ctx.userId]);const b=await c.query(`INSERT INTO baselines(org_id,project_id,sequence_no,label,created_from_schedule_version,status,captured_by,created_by,updated_by) SELECT $1,$2,COALESCE(max(sequence_no),0)+1,$3,0,$4,$5,$5,$5 FROM baselines WHERE project_id=$2 RETURNING id`,[ctx.orgId,p,'Imported '+j,data.activateBaseline?'active':'superseded',ctx.userId]);baselineId=b.rows[0].id;for(const t of baselineTasks)await c.query('INSERT INTO baseline_tasks(baseline_id,task_id,start_at,finish_at,duration_minutes,work_minutes,task_name,wbs_code) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[baselineId,t.id,t.baselineStart,t.baselineFinish,t.baselineDuration??t.duration,t.baselineWork??t.work,t.name,t.wbs]);for(const a of data.baselineAssignments??[])await c.query('INSERT INTO baseline_assignments(baseline_id,task_id,resource_id,work_minutes,units,start_at,finish_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[baselineId,a.taskId,a.resourceId,a.work,a.units,a.start,a.finish]);await this.audit.write(c,ctx,{entityType:'baseline',entityId:baselineId,action:'import_create',diff:{job:j,active:data.activateBaseline},correlationId:correlation});}
   const updated=await c.query('UPDATE projects SET updated_by=$2 WHERE id=$1 RETURNING version',[p,ctx.userId]);await c.query(`INSERT INTO job_outbox(org_id,aggregate_type,aggregate_id,aggregate_version,type,payload) VALUES($1,'project',$2,$3,'import.committed',$4),($1,'project',$2,$3,'alert.evaluate',$4),($1,'project',$2,$3,'dashboard.invalidate',$4)`,[ctx.orgId,p,updated.rows[0].version,JSON.stringify({job_id:j})]);
   const result={task_count:data.tasks.length,assignment_count:data.assignments.length,baseline_id:baselineId,commit_key:key,commit_hash:requestHash};const done=await c.query(`UPDATE import_jobs SET state='succeeded',result=$2,updated_by=$3 WHERE id=$1 RETURNING *`,[j,JSON.stringify(result),ctx.userId]);await this.audit.write(c,ctx,{entityType:'import_job',entityId:j,action:'commit',diff:{preview_id:dto.previewId,task_count:data.tasks.length},correlationId:correlation});return this.publicJob(done.rows[0]);
  });}catch(e:any){if(e.code==='40001')throw DomainError.conflict('preview_stale','並行更新，請重新預覽');if(e instanceof DomainError)throw e;await this.db.transaction(async c=>{await c.query(`UPDATE import_jobs SET state='failed',result=$2 WHERE id=$1 AND state<>'succeeded'`,[j,JSON.stringify({code:'import_failed'})]);await this.audit.write(c,ctx,{entityType:'import_job',entityId:j,action:'commit_failed',diff:{code:'import_failed'},correlationId:correlation});});console.error('exchange commit failed',correlation,e.code);throw new DomainError('import','import_failed','提交失敗，案件變更已全部回滾');}
 }
 private async generateExport(ctx:UserContext,p:string,dto:ExportDto){
  return this.db.transaction(async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');const project=await this.project(c,ctx,p);const rows=(await c.query('SELECT t.*,d.code AS system_code FROM project_tasks t LEFT JOIN disciplines d ON d.id=t.discipline_id WHERE t.project_id=$1 AND t.org_id=$2 AND t.archived_at IS NULL ORDER BY t.sort_key,t.id',[p,ctx.orgId])).rows;const deps=(await c.query('SELECT * FROM task_dependencies WHERE project_id=$1 AND archived_at IS NULL',[p])).rows;const assignments=(await c.query('SELECT a.*,r.code,r.name AS resource_name FROM resource_assignments a JOIN resources r ON r.id=a.resource_id WHERE a.project_id=$1 AND a.archived_at IS NULL ORDER BY a.id',[p])).rows;const identities=(await c.query(`SELECT * FROM external_id_map WHERE project_id=$1 AND entity_type='task'`,[p])).rows;
   const baseline=dto.baselineId?(await c.query('SELECT * FROM baselines WHERE id=$1 AND project_id=$2 AND org_id=$3',[dto.baselineId,p,ctx.orgId])).rows[0]:(await c.query(`SELECT * FROM baselines WHERE project_id=$1 AND status='active'`,[p])).rows[0];if(dto.baselineId&&!baseline)throw DomainError.notFound('Baseline');const snapshots=baseline?(await c.query('SELECT * FROM baseline_tasks WHERE baseline_id=$1',[baseline.id])).rows:[];
   const ordered:any[]=[];const children=new Map<string|null,any[]>();for(const t of rows)children.set(t.parent_task_id,[...(children.get(t.parent_task_id)??[]),t]);const stack=(children.get(null)??[]).map(t=>({t,level:1})).reverse();const seen=new Set<string>();while(stack.length){const {t,level}=stack.pop()!;if(seen.has(t.id))throw DomainError.conflict('hierarchy_cycle','工作階層循環，請修復');seen.add(t.id);ordered.push({...t,level});for(const child of [...(children.get(t.id)??[])].reverse())stack.push({t:child,level:level+1});}if(ordered.length!==rows.length)throw DomainError.conflict('hierarchy_invalid','工作有缺失父節點或階層循環');
   const ids=new Map(ordered.map((t,i)=>[t.id,String(i+1)]));const date=(v:any)=>v?new Date(v).toISOString():'';const guid=(id:string)=>identities.find(e=>e.entity_id===id&&e.system==='msproject-guid')?.external_id??id;
   const taskRows:SheetRow[]=ordered.map(t=>{const b=snapshots.find(b=>b.task_id===t.id);const a=assignments.filter(a=>a.task_id===t.id);return{'Task Name':t.name,WBS:t.wbs_code,'Outline Level':String(t.level),Start:date(t.planned_start),Finish:date(t.planned_finish),Duration:t.duration_minutes+'min',Predecessors:deps.filter(e=>e.successor_task_id===t.id).map(e=>ids.get(e.predecessor_task_id)+e.relation+(e.lag_minutes?(e.lag_minutes>0?'+':'')+e.lag_minutes+'min':'')).join(';'),'Resource Names':a.map(a=>a.resource_name).join(';'),Work:(a.reduce((n,a)=>n+a.planned_work_minutes,0)+t.unassigned_work_minutes)+'min','% Complete':String(Number(t.percent_complete)),'Baseline Start':date(b?.start_at),'Baseline Finish':date(b?.finish_at),Milestone:String(t.milestone),'Constraint Type':t.constraint_type,'Constraint Date':date(t.constraint_date),Notes:t.notes??'','Unique ID':identities.find(e=>e.entity_id===t.id&&e.system==='msproject-uid')?.external_id??ids.get(t.id)!,GUID:guid(t.id),ID:ids.get(t.id)!,'Actual Start':date(t.actual_start),'Actual Finish':date(t.actual_finish),'Remaining Duration':t.remaining_minutes===null?'':t.remaining_minutes+'min','System Code':t.system_code??'','Calendar Code':t.calendar_id??project.default_calendar_id??'','Summary':String(t.summary),'External Project':'','Task Type':t.type};});
   const assignmentRows:SheetRow[]=assignments.map(a=>({'Task GUID':guid(a.task_id),'Resource GUID':a.resource_id,'Resource Code':a.code,Units:String(a.assignment_units),'Planned Work':a.planned_work_minutes+'min','Actual Work':a.actual_work_minutes+'min','Remaining Work':a.remaining_work_minutes===null?'':a.remaining_work_minutes+'min',Start:date(a.assignment_start),Finish:date(a.assignment_finish),'Booking Type':a.booking_type,Contour:a.contour?JSON.stringify(a.contour):''}));
   const baselineAssignmentRows=baseline?(await c.query('SELECT a.*,r.code FROM baseline_assignments a LEFT JOIN resources r ON r.id=a.resource_id WHERE a.baseline_id=$1 ORDER BY a.task_id,a.resource_id',[baseline.id])).rows:[];
   const baselineSheet:SheetRow[]=[...snapshots.map(b=>({Kind:'task','Task GUID':guid(b.task_id),'Resource GUID':'','Resource Code':'',Start:date(b.start_at),Finish:date(b.finish_at),Duration:b.duration_minutes+'min',Work:b.work_minutes+'min',Units:''})),...baselineAssignmentRows.map(a=>({Kind:'assignment','Task GUID':guid(a.task_id),'Resource GUID':a.resource_id,'Resource Code':a.code??'',Start:date(a.start_at),Finish:date(a.finish_at),Duration:'',Work:a.work_minutes+'min',Units:String(a.units)}))];
   const resourceSheet:SheetRow[]=(await c.query('SELECT DISTINCT r.id,r.code,r.name,r.type,r.max_units,r.base_week_minutes FROM resources r WHERE r.org_id=$1 AND r.id=ANY($2::uuid[]) ORDER BY r.code',[ctx.orgId,[...new Set([...assignments,...baselineAssignmentRows].map(a=>a.resource_id))]])).rows.map(r=>({'Resource GUID':r.id,'Resource Code':r.code,Name:r.name,Type:r.type,'Max Units':String(r.max_units),'Base Week Minutes':r.base_week_minutes===null?'':String(r.base_week_minutes)}));
   const resourceProfiles=(await c.query('SELECT rc.*,r.code FROM resource_calendars rc JOIN resources r ON r.id=rc.resource_id WHERE rc.org_id=$1 AND rc.resource_id=ANY($2::uuid[]) AND rc.archived_at IS NULL ORDER BY rc.resource_id,rc.priority,rc.id',[ctx.orgId,[...new Set([...assignments,...baselineAssignmentRows].map(a=>a.resource_id))]])).rows;
   const resourceCalendarSheet:SheetRow[]=resourceProfiles.map(r=>({'Resource Code':r.code,'Calendar Code':r.calendar_id,'Effective From':r.effective_from??'','Effective To':r.effective_to??'',Priority:String(r.priority)}));
   const calendarIds=[...new Set([project.default_calendar_id,...ordered.map(t=>t.calendar_id),...resourceProfiles.map(r=>r.calendar_id)].filter(Boolean))];const calendarRows=(await c.query('WITH RECURSIVE selected(id) AS (SELECT id FROM calendars WHERE id=ANY($1::uuid[]) AND org_id=$2 AND archived_at IS NULL UNION SELECT c.parent_calendar_id FROM calendars c JOIN selected s ON s.id=c.id WHERE c.org_id=$2 AND c.parent_calendar_id IS NOT NULL) SELECT c.* FROM calendars c JOIN selected s ON s.id=c.id WHERE c.org_id=$2 AND c.archived_at IS NULL ORDER BY c.id',[calendarIds,ctx.orgId])).rows;
   const calendarSheet:SheetRow[]=calendarRows.map(r=>({'Calendar Code':r.id,Name:r.name,Timezone:r.timezone,'Hours Per Day':String(r.hours_per_day),'Parent Calendar Code':r.parent_calendar_id??''}));
   const includedCalendarIds=calendarRows.map(c=>c.id);const workingRows=(await c.query('SELECT * FROM calendar_working_days WHERE org_id=$1 AND calendar_id=ANY($2::uuid[]) AND archived_at IS NULL ORDER BY calendar_id,weekday,local_start',[ctx.orgId,includedCalendarIds])).rows;const exceptionRows=(await c.query('SELECT * FROM calendar_exceptions WHERE org_id=$1 AND calendar_id=ANY($2::uuid[]) AND archived_at IS NULL ORDER BY calendar_id,local_date,local_start',[ctx.orgId,includedCalendarIds])).rows;
   const exceptionSheet:SheetRow[]=[...workingRows.map(r=>({'Calendar Code':r.calendar_id,Type:'working_day',Weekday:String(r.weekday),'Local Date':'','Local Start':String(r.local_start),'Local End':String(r.local_end),'Available Minutes':''})),...exceptionRows.map(r=>({'Calendar Code':r.calendar_id,Type:'exception',Weekday:'','Local Date':r.local_date,'Local Start':r.local_start??'','Local End':r.local_end??'','Available Minutes':String(r.available_minutes)}))];
   const warnings:any[]=[];if(snapshots.some(b=>b.cost!==null)||baselineAssignmentRows.some(b=>b.cost!==null)||assignments.some(a=>a.cost!==null))warnings.push({code:'cost_not_exported',message:'Cost欄未納入此交換，金額未輸出；基準與指派成本無法由此檔還原'});if(dto.format==='csv'&&snapshots.length)warnings.push({code:'csv_baseline_detail_loss',message:'單檔CSV只保存基準起訖，基準Duration/Work/指派請使用XLSX'});if(dto.format==='csv'&&assignments.length)warnings.push({code:'csv_assignment_detail_loss',message:'單檔CSV無法保存各指派Units/工時/輪廓，請用XLSX完整交換'});if(dto.format==='csv'&&taskRows.some(r=>Object.values(r).some(v=>/^[=+@-]/.test(v))))warnings.push({code:'csv_text_protection',message:'CSV文字公式防護會加前置apostrophe；XLSX保存原文字'});
   const sheets={Tasks:{columns:[...TASK_COLUMNS,...EXTRA_COLUMNS],rows:taskRows},Assignments:{columns:['Task GUID','Resource GUID','Resource Code','Units','Planned Work','Actual Work','Remaining Work','Start','Finish','Booking Type','Contour'],rows:assignmentRows},Resources:{columns:['Resource GUID','Resource Code','Name','Type','Max Units','Base Week Minutes'],rows:resourceSheet},'Resource Calendars':{columns:['Resource Code','Calendar Code','Effective From','Effective To','Priority'],rows:resourceCalendarSheet},Exceptions:{columns:['Calendar Code','Type','Weekday','Local Date','Local Start','Local End','Available Minutes'],rows:exceptionSheet},Baselines:{columns:['Kind','Task GUID','Resource GUID','Resource Code','Start','Finish','Duration','Work','Units'],rows:baselineSheet},Calendars:{columns:['Calendar Code','Name','Timezone','Hours Per Day','Parent Calendar Code'],rows:calendarSheet},Metadata:{columns:['Key','Value'],rows:[{Key:'Schema Version',Value:String(SCHEMA_VERSION)},{Key:'Project ID',Value:p},{Key:'Baseline ID',Value:baseline?.id??''}]}};const buffers=dto.format==='csv'?writeCsv(taskRows,[...TASK_COLUMNS,...EXTRA_COLUMNS]):dto.format==='csv-package'?await writeCsvPackage(sheets):dto.format==='xml'?writeMspXml(sheets):await writeXlsx(sheets);
   const sourceSnapshot=dto.format==='csv'?{Tasks:sheets.Tasks}:sheets;const roundTrip=compareTables(sourceSnapshot,await readTables(buffers,{format:dto.format,timezone:'UTC',hoursPerDay:8}));if(!roundTrip.equal)warnings.push({code:'round_trip_difference',message:'回讀與原始欄位有 '+roundTrip.difference_count+' 項差異，請查看逐欄報告'});
   return{sourceSnapshot,bytes:buffers,report:{task_count:taskRows.length,assignment_count:assignments.length,warnings,round_trip:roundTrip,baseline_id:baseline?.id??null}};
  });
 }
 async export(ctx:UserContext,p:string,dto:ExportDto,key:string|undefined,correlation:string,asyncMode=false){
  key=this.key(key);await this.project(this.connection(),ctx,p);const hash=stableHash(dto);const old=await this.db.queryOne<any>('SELECT * FROM export_jobs WHERE project_id=$1 AND idempotency_key=$2',[p,key]);if(old){if(old.input_hash!==hash)throw DomainError.conflict('idempotency_conflict','相同key匯出選項不同');return this.publicExport(old);}
  if(asyncMode){try{return await this.db.transaction(async c=>{const r=await c.query(`INSERT INTO export_jobs(org_id,project_id,format,filters,state,idempotency_key,input_hash,initiated_by,created_by,expires_at) VALUES($1,$2,$3,$4,'pending',$5,$6,$7,$7,now()+interval '30 days') RETURNING *`,[ctx.orgId,p,dto.format,JSON.stringify({...dto}),key,hash,ctx.userId]);await c.query(`INSERT INTO exchange_worker_jobs(org_id,project_id,kind,export_job_id,created_by,updated_by) VALUES($1,$2,'render',$3,$4,$4)`,[ctx.orgId,p,r.rows[0].id,ctx.userId]);await this.audit.write(c,ctx,{entityType:'export_job',entityId:r.rows[0].id,action:'export_accepted',diff:{format:dto.format,async:true},correlationId:correlation});return this.publicExport(r.rows[0]);});}catch(e:any){if(e.code==='23505'){const found=await this.db.queryOne<any>('SELECT * FROM export_jobs WHERE project_id=$1 AND idempotency_key=$2',[p,key]);if(found?.input_hash===hash)return this.publicExport(found);}throw e;}}
  const generated=await this.generateExport(ctx,p,dto);const output=await this.storage.write(generated.bytes);try{return await this.db.transaction(async c=>{const r=await c.query(`INSERT INTO export_jobs(org_id,project_id,format,filters,state,output_key,idempotency_key,input_hash,initiated_by,created_by,expires_at) VALUES($1,$2,$3,$4,'succeeded',$5,$6,$7,$8,$8,now()+interval '30 days') RETURNING *`,[ctx.orgId,p,dto.format,JSON.stringify({...dto,report:generated.report,source_snapshot:generated.sourceSnapshot,output_hash:contentHash(generated.bytes)}),output,key,hash,ctx.userId]);await this.audit.write(c,ctx,{entityType:'export_job',entityId:r.rows[0].id,action:'export',diff:{format:dto.format,...generated.report},correlationId:correlation});return this.publicExport(r.rows[0]);});}catch(e:any){await this.storage.remove(output);if(e.code==='23505'){const found=await this.db.queryOne<any>('SELECT * FROM export_jobs WHERE project_id=$1 AND idempotency_key=$2',[p,key]);if(found?.input_hash===hash)return this.publicExport(found);}throw e;}
 }
 async roundTrip(ctx:UserContext,p:string,j:string,correlation:string){await this.getExport(ctx,p,j);const row=await this.db.queryOne<any>('SELECT filters,format FROM export_jobs WHERE id=$1 AND project_id=$2 AND org_id=$3',[j,p,ctx.orgId]);const {bytes}=await this.download(ctx,p,j);const actual=await readTables(bytes,{format:row.format,timezone:'UTC',hoursPerDay:8});const report=compareTables(row.filters.source_snapshot,actual);await this.db.transaction(async c=>{await this.audit.write(c,ctx,{entityType:'export_job',entityId:j,action:'round_trip',diff:{equal:report.equal,difference_count:report.difference_count},correlationId:correlation});});return report;}
 async getExport(ctx:UserContext,p:string,j:string){await this.project(this.connection(),ctx,p);const row=await this.db.queryOne<any>('SELECT * FROM export_jobs WHERE id=$1 AND project_id=$2 AND org_id=$3',[j,p,ctx.orgId]);if(!row)throw DomainError.notFound('匯出');return this.publicExport(row);}
 async download(ctx:UserContext,p:string,j:string){await this.getExport(ctx,p,j);const row=await this.db.queryOne<any>('SELECT state,output_key,filters,format,expires_at FROM export_jobs WHERE id=$1',[j]);if(row.state!=='succeeded'||!row.output_key)throw DomainError.conflict('export_pending','匯出尚未完成渲染，請稍後再下載');if(new Date(row.expires_at)<new Date())throw DomainError.conflict('export_expired','匯出檔已過期，請重新產生');const bytes=await this.storage.read(row.output_key);if(contentHash(bytes)!==row.filters.output_hash)throw new DomainError('infrastructure','output_corrupt','輸出檔案校驗失敗');return{bytes,format:row.format};}
}
