import {useEffect,useState,useRef} from 'react';
import {fetchGanttOptions,exchangeRequest,downloadExchange,type ExchangeJob,type ExchangePreview} from './api';
import {LoadingState,EmptyState,NoPermissionState} from './components/States';
export function ExchangePage(){
 const [projects,setProjects]=useState<{id:string;name:string}[]>([]),[project,setProject]=useState(''),[format,setFormat]=useState('csv'),[file,setFile]=useState<File|null>(null),[job,setJob]=useState<ExchangeJob|null>(null),[preview,setPreview]=useState<ExchangePreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[forbidden,setForbidden]=useState(false),[status,setStatus]=useState(''),[mapping,setMapping]=useState<Record<string,string>>({}),[columns,setColumns]=useState<string[]>([]),[anchor,setAnchor]=useState(''),[existingAnchor,setExistingAnchor]=useState(''),[mode,setMode]=useState('create-only'),[dateFormat,setDateFormat]=useState(''),[timezone,setTimezone]=useState('Asia/Taipei'),[ack,setAck]=useState(false),[resourceMap,setResourceMap]=useState<Record<string,string>>({}),[allocations,setAllocations]=useState<Record<string,Record<string,number>>>({}),[options,setOptions]=useState<{resources:{id:string;name:string;code:string}[];anchors:{id:string;name:string}[]}>({resources:[],anchors:[]}),[page,setPage]=useState(0),[changePage,setChangePage]=useState(0),[baseline,setBaseline]=useState(false),[exportFormat,setExportFormat]=useState('xlsx'),[startTime,setStartTime]=useState(''),[finishTime,setFinishTime]=useState(''),[predecessorMode,setPredecessorMode]=useState('id');
 const uploadKey=useRef(crypto.randomUUID()),commitKey=useRef(crypto.randomUUID());const revision=useRef(0);
 async function load(){try{const r=await fetchGanttOptions();if(r.status===403){setForbidden(true);return;}if(!r.body||!Array.isArray(r.body.projects))throw new Error('案件清單載入失敗');setProjects(r.body.projects);setError('');}catch(e){setError(e instanceof Error?e.message:'載入失敗');}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{revision.current++;setJob(null);setPreview(null);setAnchor('');setExistingAnchor('');setStatus('');setMapping({});setResourceMap({});setAllocations({});if(!project)return;let active=true;void Promise.all([exchangeRequest(`/projects/${project}/exchange/schema`),exchangeRequest(`/projects/${project}/exchange/options`)]).then(([s,o])=>{if(active){setColumns([...s.columns,...s.extras]);setOptions(o);setForbidden(false);}}).catch(e=>{if(active){setError(e.message);setForbidden(e.status===403||e.status===404);}});return()=>{active=false;};},[project]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');const current=revision.current;try{await fn();}catch(e){if(current===revision.current){setError(e instanceof Error?e.message:'操作失敗');setForbidden((e as {status?:number}).status===403);}}finally{if(current===revision.current)setBusy(false);}}
 async function upload(){if(!file||!project)return;const current=revision.current;const form=new FormData();form.append('file',file);form.append('format',format);form.append('timezone',timezone);const r=await exchangeRequest(`/projects/${project}/imports`,'POST',form,{'Idempotency-Key':uploadKey.current});if(current===revision.current){setJob(r);setPreview(null);setStatus('檔案已通過掃描，請確認映射與掛件錨點');}}
 async function makePreview(){if(!job)return;const current=revision.current;const r=await exchangeRequest(`/projects/${project}/imports/${job.id}/previews`,'POST',{mode,mapping,...(anchor?{anchorKey:anchor}:{}),...(existingAnchor?{anchorTaskId:existingAnchor}:{}),...(dateFormat?{dateFormat}:{}),...(startTime?{startTime}:{}),...(finishTime?{finishTime}:{}),predecessorMode,resourceMap,workAllocations:allocations,acknowledgeWarnings:ack,activateBaseline:baseline},{'If-Match':String(job.version)});if(current===revision.current){setPreview(r);setJob({...job,version:r.job_version});setPage(0);setChangePage(0);setStatus(r.can_commit?'預覽已通過，可確認提交':'請先修正下列錯誤，再重新預覽');}}
 async function commit(){if(!preview||!job)return;const r=await exchangeRequest(`/projects/${project}/imports/${job.id}/commit`,'POST',{previewId:preview.id,previewHash:preview.payload_hash},{'Idempotency-Key':commitKey.current,'If-Match':String(preview.job_version)});setJob(r);setStatus('匯入成功，所有案件變更已一併提交');setPreview(null);}
 async function exportFile(){const r=await exchangeRequest(`/projects/${project}/exports`,'POST',{format:exportFormat},{'Idempotency-Key':crypto.randomUUID()});setStatus(r.report?.warnings?.length?'匯出完成；轉換警告：'+r.report.warnings.map((w:{message:string})=>w.message).join('；'):'匯出完成');await downloadExchange(project,r.id,exportFormat);}
 const headers=job?.result.file_info?.headers??[];
 if(forbidden)return <main className="exchange-page"><h1>Project 匯入與匯出</h1><NoPermissionState/><button onClick={()=>{setForbidden(false);void load();}}>重新載入</button></main>;
 return <main className="exchange-page" aria-busy={busy}><h1>Project 匯入與匯出</h1><p>預覽不修改案件；確認提交後才更新工作、指派與基準。</p>
 {error&&<div role="alert"><p>{error}</p><button disabled={busy} onClick={()=>{setError('');if(!projects.length)void load();}}>修正後重試</button></div>}
 <label>案件<select aria-label="交換案件" disabled={busy} value={project} onChange={e=>setProject(e.target.value)}><option value="">請選擇案件</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 {!projects.length&&!error?<EmptyState message="尚無可操作案件，請先建立案件。"/>:null}
 {project&&<><section aria-label="上傳與映射"><fieldset disabled={busy}><legend>匯入設定</legend><h2>1. 上傳檔案</h2><label>格式<select value={format} disabled={busy} onChange={e=>{setFormat(e.target.value);setJob(null);setPreview(null);uploadKey.current=crypto.randomUUID();}}><option value="csv">CSV</option><option value="xlsx">Excel XLSX</option></select></label><label>來源時區<input value={timezone} onChange={e=>setTimezone(e.target.value)} disabled={busy}/></label><label>檔案<input type="file" accept={format==='csv'?'.csv':'.xlsx'} disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);setJob(null);setPreview(null);uploadKey.current=crypto.randomUUID();}}/></label><button disabled={busy||!file} onClick={()=>void action(upload)}>上傳與掃描</button>
 {job&&job.state!=='succeeded'&&<><h2>2. 欄位與匯入設定</h2><p>作業 {job.id}；掃描 {job.scan_state}</p><div className="exchange-mapping">{headers.map(h=><label key={h}>{h}<select aria-label={`映射 ${h}`} value={mapping[h]??(columns.includes(h)?h:'')} onChange={e=>{setMapping({...mapping,[h]:e.target.value});setPreview(null);}}><option value="">請選欄位</option>{columns.map(c=><option key={c}>{c}</option>)}</select></label>)}</div>
 <label>處理方式<select value={mode} onChange={e=>{setMode(e.target.value);setPreview(null);}}><option value="create-only">僅新增</option><option value="upsert">依外部識別更新</option></select></label><label>日期格式（ISO 可留空）<input value={dateFormat} onChange={e=>{setDateFormat(e.target.value);setPreview(null);}} placeholder="dd/MM/yyyy HH:mm"/></label>
 <label>純日期開始時間<input type="time" value={startTime} onChange={e=>{setStartTime(e.target.value);setPreview(null);}}/></label><label>純日期完成時間<input type="time" value={finishTime} onChange={e=>{setFinishTime(e.target.value);setPreview(null);}}/></label><label>前置參照<select value={predecessorMode} onChange={e=>{setPredecessorMode(e.target.value);setPreview(null);}}><option value="id">ID</option><option value="uid">Unique ID（須來源明確使用）</option></select></label>
 <label>檔案中的掛件錨點<select aria-label="掛件錨點" value={anchor} onChange={e=>{setAnchor(e.target.value);setExistingAnchor('');setPreview(null);}}><option value="">請選擇</option>{(preview?.changes.map(t=>({key:t.key,name:t.name,wbs:''}))??job.result.file_info?.anchor_candidates??[]).map(a=><option key={a.key} value={a.key}>{a.wbs} {a.name}</option>)}</select></label><label>或確認現有掛件錨點<select value={existingAnchor} onChange={e=>{setExistingAnchor(e.target.value);setAnchor('');setPreview(null);}}><option value="">不使用</option>{options.anchors?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
 <label><input type="checkbox" checked={baseline} onChange={e=>{setBaseline(e.target.checked);setPreview(null);}}/>將本次匯入的新版 Baseline 設為 active（舊版保留）</label><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>已閱讀並確認預覽警告</label><button disabled={busy} onClick={()=>void action(makePreview)}>產生預覽／重新驗證</button></>}
 </fieldset></section>
 {preview&&<section aria-label="預覽驗證"><h2>3. 預覽與確認</h2><p>{preview.task_count} 項工作；{preview.can_commit?'可提交':'尚有錯誤'}</p><ul>{preview.issues.slice(page*50,page*50+50).map((i,n)=><li key={n}>[{i.severity==='error'?'錯誤':'注意'}] 第 {i.row} 列 {i.field}：{i.message}</li>)}</ul>{preview.issues.length>50&&<div><button disabled={!page} onClick={()=>setPage(page-1)}>上一頁問題</button><span>{page+1}／{Math.ceil(preview.issues.length/50)}</span><button disabled={(page+1)*50>=preview.issues.length} onClick={()=>setPage(page+1)}>下一頁問題</button></div>}
 {preview.changes.slice(changePage*100,(changePage+1)*100).map(t=><div key={t.key}><p>{t.name}：{t.action==='create'?'新增':'更新'}</p>{t.resources?.map(name=><div key={name}><label>{name} 資源<select value={resourceMap[name]??''} onChange={e=>{setResourceMap({...resourceMap,[name]:e.target.value});setPreview({...preview,can_commit:false});}}><option value="">來源精確匹配</option>{options.resources.map(r=><option key={r.id} value={r.id}>{r.name}（{r.code}）</option>)}</select></label>{t.resources!.length>1&&<label>{name} 分配工時（分鐘）<input type="number" min="0" value={allocations[t.key]?.[name]??''} onChange={e=>{setAllocations({...allocations,[t.key]:{...allocations[t.key],[name]:Number(e.target.value)}});setPreview({...preview,can_commit:false});}}/></label>}</div>)}</div>)}
 {preview.changes.length>100&&<div aria-label="工作預覽分頁"><button disabled={!changePage} onClick={()=>setChangePage(changePage-1)}>上一頁工作</button><span>{changePage+1}／{Math.ceil(preview.changes.length/100)}</span><button disabled={(changePage+1)*100>=preview.changes.length} onClick={()=>setChangePage(changePage+1)}>下一頁工作</button></div>}
 <button disabled={busy||!preview.can_commit} onClick={()=>void action(commit)}>確認提交全部變更</button><button disabled={busy} onClick={()=>setPreview(null)}>取消預覽</button></section>}
 <section aria-label="匯出"><h2>匯出</h2><label>匯出格式<select value={exportFormat} onChange={e=>setExportFormat(e.target.value)}><option value="xlsx">XLSX（完整指派）</option><option value="csv">CSV（工作映射）</option></select></label><button disabled={busy} onClick={()=>void action(exportFile)}>產生並下載</button></section></>}
 {busy&&<LoadingState/>}{status&&<p role="status">{status}</p>}
 </main>;
}
