import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {api,headers,BASE,createProject,db,closeDb,ORG,PM_USER} from './helpers.mjs';
const require=createRequire(import.meta.url);
const {writeCsv,writeXlsx}=require('../../dist/exchange/formats.js');
const {TASK_COLUMNS,EXTRA_COLUMNS}=require('../../dist/exchange/model.js');
const source=()=>[{'Task Name':'設計','WBS':'1','Outline Level':'1',Start:'2027-01-08T09:00+08:00',Finish:'2027-01-08T18:00+08:00',Duration:'1d',Predecessors:'','Resource Names':'',Work:'8h','% Complete':'0',Milestone:'false','Constraint Type':'ASAP','Unique ID':'101',ID:'1',GUID:randomUUID()},{'Task Name':'掛件','WBS':'0.0','Outline Level':'1',Start:'2027-01-11T18:00+08:00',Finish:'2027-01-11T18:00+08:00',Duration:'0d',Predecessors:'1FS','Resource Names':'',Work:'0h','% Complete':'0',Milestone:'true','Constraint Type':'ASAP','Unique ID':'102',ID:'2',GUID:randomUUID()}];
async function upload(p,rows,key=randomUUID(),roles='PM',format='csv'){const bytes=format==='csv'?writeCsv(rows,[...TASK_COLUMNS,...EXTRA_COLUMNS]):await writeXlsx({Tasks:{columns:[...TASK_COLUMNS,...EXTRA_COLUMNS],rows}});const form=new FormData();form.append('file',new Blob([bytes]),'project.'+format);form.append('format',format);const h=headers(roles);delete h['Content-Type'];h['Idempotency-Key']=key;const r=await fetch(BASE+`/projects/${p}/imports`,{method:'POST',headers:h,body:form});return{status:r.status,body:await r.json()};}
async function preview(p,j,rows,extra={}){const r=await fetch(BASE+`/projects/${p}/imports/${j.id}/previews`,{method:'POST',headers:{...headers('PM'),'If-Match':String(j.version)},body:JSON.stringify({anchorKey:'guid:'+rows[1].GUID,...extra})});return{status:r.status,body:await r.json()};}
async function commit(p,j,v,key=randomUUID()){const r=await fetch(BASE+`/projects/${p}/imports/${j.id}/commit`,{method:'POST',headers:{...headers('PM'),'If-Match':String(v.job_version),'Idempotency-Key':key},body:JSON.stringify({previewId:v.id,previewHash:v.payload_hash})});return{status:r.status,body:await r.json()};}

test('P5 原子CSV新增/預覽無業務寫入/同key提交重放/稽核與outbox',async()=>{const p=await createProject(),rows=source();const u=await upload(p,rows);assert.equal(u.status,201,JSON.stringify(u.body));const v=await preview(p,u.body,rows);assert.equal(v.status,201,JSON.stringify(v.body));assert.equal(v.body.can_commit,true,JSON.stringify(v.body));assert.equal((await db().query('SELECT count(*)::int AS n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,0);const key=randomUUID(),c=await commit(p,u.body,v.body,key);assert.equal(c.status,201,JSON.stringify(c.body));assert.equal(c.body.state,'succeeded');const replay=await commit(p,u.body,v.body,key);assert.equal(replay.body.id,c.body.id);assert.equal((await db().query('SELECT count(*)::int AS n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,2);assert.ok((await db().query("SELECT count(*)::int AS n FROM audit_logs WHERE entity_id=$1 AND action='commit'",[u.body.id])).rows[0].n===1);assert.equal((await db().query("SELECT count(*)::int AS n FROM job_outbox WHERE aggregate_id=$1 AND type='import.committed'",[p])).rows[0].n,1);});
test('P5 preview stale：來源預覽後修改案件→409，無task寫入',async()=>{const p=await createProject(),rows=source(),u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));await db().query('UPDATE projects SET name=name||\' changed\' WHERE id=$1',[p]);const c=await commit(p,u.body,v.body);assert.equal(c.status,409,JSON.stringify(c.body));assert.equal(c.body.code,'preview_stale');assert.equal((await db().query('SELECT count(*)::int n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,0);});
test('P5 不可變預覽、多人Work未決策阻擋',async()=>{const p=await createProject(),rows=source();rows[0]['Resource Names']='unknownA;unknownB';const u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,false);assert.ok(v.body.issues.some(x=>x.code==='work_allocation_required'));await assert.rejects(db().query("UPDATE import_preview_versions SET errors='[]' WHERE id=$1",[v.body.id]),/immutable/);assert.equal((await commit(p,u.body,v.body)).status,422);});
test('P5 scope Viewer/跨案job/同upload key異payload',async()=>{const p=await createProject(),other=await createProject(),rows=source();assert.equal((await upload(p,rows,randomUUID(),'Viewer')).status,403);const key=randomUUID(),u=await upload(p,rows,key);assert.equal((await api('GET',`/projects/${other}/imports/${u.body.id}`)).status,404);rows[0]['Task Name']='changed';assert.equal((await upload(p,rows,key)).status,409);});
test('P5 XLSX import→export→parse round-trip包含Work及階層',async()=>{const p=await createProject(),rows=source(),u=await upload(p,rows,randomUUID(),'PM','xlsx'),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));assert.equal((await commit(p,u.body,v.body)).body.state,'succeeded');const r=await fetch(BASE+`/projects/${p}/exports`,{method:'POST',headers:{...headers('PM'),'Idempotency-Key':randomUUID()},body:JSON.stringify({format:'xlsx'})});const e=await r.json();assert.equal(r.status,201,JSON.stringify(e));const file=await fetch(BASE+`/projects/${p}/exports/${e.id}/download`,{headers:headers('PM')});assert.equal(file.status,200);const {parseExchange}=require('../../dist/exchange/parser.js');const parsed=await parseExchange(Buffer.from(await file.arrayBuffer()),{format:'xlsx',timezone:'Asia/Taipei',hoursPerDay:8});assert.deepEqual(parsed.issues,[]);assert.equal(parsed.tasks.length,2);assert.equal(parsed.tasks[0].work,480);assert.equal(parsed.dependencies.length,1);});
test('P5 來源日期違反FS時不提交',async()=>{const p=await createProject(),rows=source();rows[0].Finish='2027-01-12T18:00+08:00';const u=await upload(p,rows),v=await preview(p,u.body,rows);assert.ok(v.body.issues.some(x=>x.code==='anchor_conflict'));assert.equal(v.body.can_commit,false);});
test.after(()=>closeDb());
