import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {api,headers,BASE,createProject,db,closeDb,ORG,PM_USER} from './helpers.mjs';
const require=createRequire(import.meta.url);
const {writeCsv,writeXlsx}=require('../../dist/exchange/formats.js');
const {TASK_COLUMNS,EXTRA_COLUMNS}=require('../../dist/exchange/model.js');
const source=()=>[{'Task Name':'設計','WBS':'1','Outline Level':'1',Start:'2027-01-08T09:00+08:00',Finish:'2027-01-08T18:00+08:00',Duration:'1d',Predecessors:'','Resource Names':'',Work:'8h','% Complete':'0',Milestone:'false','Constraint Type':'ASAP','Unique ID':'101',ID:'1',GUID:randomUUID()},{'Task Name':'掛件','WBS':'0.0','Outline Level':'1',Start:'2027-01-11T18:00+08:00',Finish:'2027-01-11T18:00+08:00',Duration:'0d',Predecessors:'1FS','Resource Names':'',Work:'0h','% Complete':'0',Milestone:'true','Constraint Type':'ASAP','Unique ID':'102',ID:'2',GUID:randomUUID()}];
async function upload(p,rows,key=randomUUID(),roles='PM',format='csv'){const bytes=format==='csv'?writeCsv(rows,[...TASK_COLUMNS,...EXTRA_COLUMNS]):await writeXlsx({Tasks:{columns:[...TASK_COLUMNS,...EXTRA_COLUMNS],rows}});const form=new FormData();form.append('file',new Blob([bytes]),'project.'+format);form.append('format',format);const h=headers(roles);delete h['Content-Type'];h['Idempotency-Key']=key;const r=await fetch(BASE+`/projects/${p}/imports`,{method:'POST',headers:h,body:form});return{status:r.status,body:await r.json()};}
async function preview(p,j,rows,extra={}){const r=await fetch(BASE+`/projects/${p}/imports/${j.id}/previews`,{method:'POST',headers:{...headers('PM'),'If-Match':String(j.version)},body:JSON.stringify({anchorKey:'guid:'+rows[1].GUID,...extra})});return{status:r.status,body:await r.json()};}
async function commit(p,j,v,key=randomUUID()){const r=await fetch(BASE+`/projects/${p}/imports/${j.id}/commit`,{method:'POST',headers:{...headers('PM'),'If-Match':String(v.job_version),'Idempotency-Key':key},body:JSON.stringify({previewId:v.id,previewHash:v.payload_hash})});return{status:r.status,body:await r.json()};}

test('P5 原子CSV新增/預覽無業務寫入/同key提交重放/稽核與outbox',async()=>{const p=await createProject(),rows=source();const u=await upload(p,rows);assert.equal(u.status,201,JSON.stringify(u.body));const v=await preview(p,u.body,rows);assert.equal(v.status,201,JSON.stringify(v.body));assert.equal(v.body.can_commit,true,JSON.stringify(v.body));assert.equal((await db().query('SELECT count(*)::int AS n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,0);const key=randomUUID(),c=await commit(p,u.body,v.body,key);assert.equal(c.status,201,JSON.stringify(c.body));assert.equal(c.body.state,'succeeded');const replay=await commit(p,u.body,v.body,key);assert.equal(replay.body.id,c.body.id);assert.equal((await db().query('SELECT count(*)::int AS n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,2);assert.ok((await db().query("SELECT count(*)::int AS n FROM audit_logs WHERE entity_id=$1 AND action='commit'",[u.body.id])).rows[0].n===1);assert.equal((await db().query("SELECT count(*)::int AS n FROM job_outbox WHERE aggregate_id=$1 AND type='import.committed'",[p])).rows[0].n,1);});
test('P5 preview stale：來源預覽後修改案件→409，無task寫入',async()=>{const p=await createProject(),rows=source(),u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));await db().query('UPDATE projects SET name=name||\' changed\' WHERE id=$1',[p]);const c=await commit(p,u.body,v.body);assert.equal(c.status,409,JSON.stringify(c.body));assert.equal(c.body.code,'preview_stale');assert.equal((await db().query('SELECT count(*)::int n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,0);});
test('P5 不可變預覽、多人Work未決策阻擋',async()=>{const p=await createProject(),rows=source();rows[0]['Resource Names']='unknownA;unknownB';const u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,false);assert.ok(v.body.issues.some(x=>x.code==='work_allocation_required'));await assert.rejects(db().query("UPDATE import_preview_versions SET errors='[]' WHERE id=$1",[v.body.id]),/immutable/);assert.equal((await commit(p,u.body,v.body)).status,422);});
test('P5 scope Viewer/跨案job/同upload key異payload',async()=>{const p=await createProject(),other=await createProject(),rows=source();assert.equal((await upload(p,rows,randomUUID(),'Viewer')).status,403);const key=randomUUID(),u=await upload(p,rows,key);assert.equal((await api('GET',`/projects/${other}/imports/${u.body.id}`)).status,404);rows[0]['Task Name']='changed';assert.equal((await upload(p,rows,key)).status,409);});
test('P5 XLSX import→export→parse round-trip包含Work及階層',async()=>{const p=await createProject(),rows=source(),u=await upload(p,rows,randomUUID(),'PM','xlsx'),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));assert.equal((await commit(p,u.body,v.body)).body.state,'succeeded');const r=await fetch(BASE+`/projects/${p}/exports`,{method:'POST',headers:{...headers('PM'),'Idempotency-Key':randomUUID()},body:JSON.stringify({format:'xlsx'})});const e=await r.json();assert.equal(r.status,201,JSON.stringify(e));const file=await fetch(BASE+`/projects/${p}/exports/${e.id}/download`,{headers:headers('PM')});assert.equal(file.status,200);const {parseExchange}=require('../../dist/exchange/parser.js');const parsed=await parseExchange(Buffer.from(await file.arrayBuffer()),{format:'xlsx',timezone:'Asia/Taipei',hoursPerDay:8});assert.deepEqual(parsed.issues,[]);assert.equal(parsed.tasks.length,2);assert.equal(parsed.tasks[0].work,480);assert.equal(parsed.dependencies.length,1);});
test('P5 來源日期違反FS時不提交',async()=>{const p=await createProject(),rows=source();rows[0].Finish='2027-01-12T18:00+08:00';const u=await upload(p,rows),v=await preview(p,u.body,rows);assert.ok(v.body.issues.some(x=>x.code==='anchor_conflict'));assert.equal(v.body.can_commit,false);});


test('P5 半途DB拒絕：前一列/身分/指派/outbox全部回滾，保留失敗稽核',async()=>{
 const p=await createProject(),rows=source(),u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));
 const suffix=randomUUID().replaceAll('-',''),fn='exchange_fault_'+suffix,tr='exchange_fault_'+suffix;
 try{
  await db().query(`CREATE FUNCTION ${fn}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.project_id='${p}'::uuid AND NEW.wbs_code='0.0' THEN RAISE EXCEPTION 'test injected second row failure'; END IF; RETURN NEW; END $$`);
  await db().query(`CREATE TRIGGER ${tr} BEFORE INSERT ON project_tasks FOR EACH ROW EXECUTE FUNCTION ${fn}()`);
  const c=await commit(p,u.body,v.body);assert.equal(c.status,422,JSON.stringify(c.body));assert.equal(c.body.code,'import_failed');
  for(const table of ['project_tasks','external_id_map','resource_assignments','task_dependencies'])assert.equal((await db().query(`SELECT count(*)::int n FROM ${table} WHERE project_id=$1`,[p])).rows[0].n,0,table);
  assert.equal((await db().query("SELECT count(*)::int n FROM job_outbox WHERE aggregate_id=$1 AND type='import.committed'",[p])).rows[0].n,0);
  assert.equal((await db().query("SELECT count(*)::int n FROM audit_logs WHERE entity_id=$1 AND action='commit_failed'",[u.body.id])).rows[0].n,1);
 }finally{await db().query(`DROP TRIGGER IF EXISTS ${tr} ON project_tasks`);await db().query(`DROP FUNCTION IF EXISTS ${fn}()`);}
});
test('P5 upsert未提供Notes/Start/Finish不得清空既有值，既有相依保留',async()=>{
 const p=await createProject(),rows=source();rows[0].Notes='保留說明';let u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal((await commit(p,u.body,v.body)).body.state,'succeeded');
 const columns=['Task Name','WBS','Outline Level','Duration','Unique ID','GUID'];const reduced=rows.map(r=>({...r,'Task Name':r['Task Name']+'新名稱'}));
 const form=new FormData();form.append('file',new Blob([writeCsv(reduced,columns)]),'project.csv');form.append('format','csv');const h=headers('PM');delete h['Content-Type'];h['Idempotency-Key']=randomUUID();const response=await fetch(BASE+`/projects/${p}/imports`,{method:'POST',headers:h,body:form});u={body:await response.json()};assert.equal(response.status,201);
 v=await preview(p,u.body,reduced,{mode:'upsert'});assert.equal(v.body.can_commit,true,JSON.stringify(v.body));const c=await commit(p,u.body,v.body);assert.equal(c.body.state,'succeeded',JSON.stringify(c.body));
 const stored=(await db().query("SELECT * FROM project_tasks WHERE project_id=$1 AND wbs_code='1'",[p])).rows[0];assert.equal(stored.notes,'保留說明');assert.equal(new Date(stored.planned_start).toISOString(),'2027-01-08T01:00:00.000Z');assert.equal(stored.unassigned_work_minutes,480);
 assert.equal((await db().query('SELECT count(*)::int n FROM task_dependencies WHERE project_id=$1 AND archived_at IS NULL',[p])).rows[0].n,1);
});


test('P5 完整XLSX：Task/Assignment Baseline工時獨立，跨案重匯保存不可變快照',async()=>{
 const p=await createProject(),rows=source(),resource=randomUUID(),code='P5-'+randomUUID();await db().query('INSERT INTO resources(id,org_id,code,name,created_by) VALUES($1,$2,$3,$4,$5)',[resource,ORG,code,'交換資源 '+code,PM_USER]);rows[0]['Baseline Start']='2027-01-07T09:00+08:00';rows[0]['Baseline Finish']='2027-01-08T18:00+08:00';
 const sheets={Tasks:{columns:[...TASK_COLUMNS,...EXTRA_COLUMNS],rows},Assignments:{columns:['Task GUID','Resource Code','Units','Planned Work','Actual Work','Remaining Work','Start','Finish','Booking Type','Contour'],rows:[{'Task GUID':rows[0].GUID,'Resource Code':code,Units:'0.5','Planned Work':'480min','Actual Work':'0min','Remaining Work':'480min',Start:rows[0].Start,Finish:rows[0].Finish,'Booking Type':'committed',Contour:''}]},Baselines:{columns:['Kind','Task GUID','Resource Code','Start','Finish','Duration','Work','Units'],rows:[{Kind:'task','Task GUID':rows[0].GUID,Start:rows[0]['Baseline Start'],Finish:rows[0]['Baseline Finish'],Duration:'960min',Work:'600min'},{Kind:'assignment','Task GUID':rows[0].GUID,'Resource Code':code,Start:rows[0]['Baseline Start'],Finish:rows[0]['Baseline Finish'],Work:'600min',Units:'0.25'}]}};
 async function uploadBytes(project,bytes){const form=new FormData();form.append('file',new Blob([bytes]),'project.xlsx');form.append('format','xlsx');const h=headers('PM');delete h['Content-Type'];h['Idempotency-Key']=randomUUID();const r=await fetch(BASE+`/projects/${project}/imports`,{method:'POST',headers:h,body:form});assert.equal(r.status,201);return await r.json();}
 let job=await uploadBytes(p,await writeXlsx(sheets));let v=await preview(p,job,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));const done=await commit(p,job,v.body);assert.equal(done.body.state,'succeeded',JSON.stringify(done.body));const b=done.body.result.baseline_id;assert.ok(b);
 assert.equal((await db().query('SELECT work_minutes FROM baseline_tasks WHERE baseline_id=$1',[b])).rows[0].work_minutes,600);assert.equal((await db().query('SELECT units::float FROM baseline_assignments WHERE baseline_id=$1',[b])).rows[0].units,.25);
 assert.equal((await db().query('SELECT status FROM baselines WHERE id=$1',[b])).rows[0].status,'superseded');
 const r=await fetch(BASE+`/projects/${p}/exports`,{method:'POST',headers:{...headers('PM'),'Idempotency-Key':randomUUID()},body:JSON.stringify({format:'xlsx',baselineId:b})});const e=await r.json();assert.equal(r.status,201,JSON.stringify(e));const file=await fetch(BASE+`/projects/${p}/exports/${e.id}/download`,{headers:headers('PM')});const bytes=Buffer.from(await file.arrayBuffer());
 const target=await createProject();job=await uploadBytes(target,bytes);v=await preview(target,job,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));const imported=await commit(target,job,v.body);assert.equal(imported.body.state,'succeeded',JSON.stringify(imported.body));const newBaseline=imported.body.result.baseline_id;
 const snapshot=(await db().query('SELECT duration_minutes,work_minutes FROM baseline_tasks WHERE baseline_id=$1',[newBaseline])).rows[0];assert.deepEqual(snapshot,{duration_minutes:960,work_minutes:600});assert.equal((await db().query('SELECT planned_work_minutes FROM resource_assignments WHERE project_id=$1 AND archived_at IS NULL',[target])).rows[0].planned_work_minutes,480);
 await assert.rejects(db().query('UPDATE baseline_assignments SET work_minutes=0 WHERE baseline_id=$1',[newBaseline]),/immutable/);
});


test('P5 CSV package API上傳→提交→匯出保留公式樣文字且不可跨案下載',async()=>{
 const {writeCsvPackage,readCsvPackage}=require('../../dist/exchange/csv-package.js');const p=await createProject(),rows=source();rows[0]['Task Name']='=文字名稱';rows[0].Notes="'原文";
 const bytes=await writeCsvPackage({Tasks:{columns:[...TASK_COLUMNS,...EXTRA_COLUMNS],rows}});const form=new FormData();form.append('file',new Blob([bytes],{type:'application/zip'}),'project.zip');form.append('format','csv-package');const h=headers('PM');delete h['Content-Type'];h['Idempotency-Key']=randomUUID();const r=await fetch(BASE+`/projects/${p}/imports`,{method:'POST',headers:h,body:form});const job=await r.json();assert.equal(r.status,201,JSON.stringify(job));const v=await preview(p,job,rows);assert.equal(v.body.can_commit,true,JSON.stringify(v.body));assert.equal((await commit(p,job,v.body)).body.state,'succeeded');
 const response=await fetch(BASE+`/projects/${p}/exports`,{method:'POST',headers:{...headers('PM'),'Idempotency-Key':randomUUID()},body:JSON.stringify({format:'csv-package'})});const e=await response.json();assert.equal(response.status,201,JSON.stringify(e));const file=await fetch(BASE+`/projects/${p}/exports/${e.id}/download`,{headers:headers('PM')});assert.equal(file.headers.get('content-type'),'application/zip');assert.match(file.headers.get('content-disposition'),/\.zip/);const sheets=await readCsvPackage(Buffer.from(await file.arrayBuffer()),{format:'csv-package',timezone:'Asia/Taipei',hoursPerDay:8});assert.equal(sheets.Tasks[0]['Task Name'],'=文字名稱');assert.equal(sheets.Tasks[0].Notes,"'原文");const report=await api('POST',`/projects/${p}/exchange/round-trip`,{body:{exportJobId:e.id}});assert.equal(report.status,201,JSON.stringify(report.body));assert.equal(report.body.equal,true,JSON.stringify(report.body));const other=await createProject();assert.equal((await api('GET',`/projects/${other}/exports/${e.id}/download`)).status,404);
});


test('P5 非法null Units不得當作已確認1.0，預覽拒絕且無指派寫入',async()=>{const p=await createProject(),rows=source(),id=randomUUID(),name='P5 NULL '+randomUUID();await db().query('INSERT INTO resources(id,org_id,code,name) VALUES($1,$2,$3,$4)',[id,ORG,randomUUID(),name]);rows[0]['Resource Names']=name;const u=await upload(p,rows),v=await preview(p,u.body,rows,{units:{[name]:null},acknowledgeWarnings:true});assert.equal(v.body.can_commit,false);assert.ok(v.body.issues.some(x=>x.code==='units_invalid'));assert.equal((await commit(p,u.body,v.body)).status,422);assert.equal((await db().query('SELECT count(*)::int n FROM resource_assignments WHERE project_id=$1',[p])).rows[0].n,0);});
test('P5 來源日期須遵守日曆/Duration/限制，不以引擎另算可行日期掩蓋',async()=>{
 for(const kind of ['calendar','duration','constraint']){const p=await createProject(),rows=source();if(kind==='calendar'){rows[0].Start='2027-01-09T09:00+08:00';rows[0].Finish='2027-01-11T18:00+08:00';}if(kind==='duration')rows[0].Duration='2d';if(kind==='constraint'){rows[0]['Constraint Type']='MFO';rows[0]['Constraint Date']='2027-01-07T18:00+08:00';}const u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,false,JSON.stringify(v.body));assert.ok(v.body.issues.some(i=>i.code==='source_'+kind+'_conflict'),JSON.stringify(v.body));assert.equal((await db().query('SELECT count(*)::int n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,0);}
});


test('P5 匯出同key回應形狀與檔案固定，不重建job；不同格式409',async()=>{const p=await createProject(),key=randomUUID();const request=async format=>{const r=await fetch(BASE+`/projects/${p}/exports`,{method:'POST',headers:{...headers('PM'),'Idempotency-Key':key},body:JSON.stringify({format})});return {status:r.status,body:await r.json()};};const first=await request('csv'),again=await request('csv');assert.equal(first.status,201,JSON.stringify(first.body));assert.equal(again.status,201,JSON.stringify(again.body));assert.deepEqual(again.body,first.body);assert.equal((await db().query('SELECT count(*)::int n FROM export_jobs WHERE project_id=$1 AND idempotency_key=$2',[p,key])).rows[0].n,1);const changed=await request('xlsx');assert.equal(changed.status,409);assert.equal(changed.body.code,'idempotency_conflict');});


test('P5 解析器升版拒絕舊版不可變預覽，原始預覽歷史仍保留',async()=>{const p=await createProject(),rows=source(),u=await upload(p,rows),v=await preview(p,u.body,rows);assert.equal(v.body.can_commit,true);const legacy=(await db().query('INSERT INTO import_preview_versions(org_id,project_id,import_job_id,sequence_no,parser_version,payload,payload_hash,vector_hash,decision_hash,errors,warnings,created_by) SELECT org_id,project_id,import_job_id,sequence_no+1,1,payload,payload_hash,vector_hash,decision_hash,errors,warnings,created_by FROM import_preview_versions WHERE id=$1 RETURNING id',[v.body.id])).rows[0];const rejected=await commit(p,u.body,{...v.body,id:legacy.id});assert.equal(rejected.status,409,JSON.stringify(rejected.body));assert.equal(rejected.body.code,'preview_stale');assert.equal((await db().query('SELECT count(*)::int n FROM project_tasks WHERE project_id=$1',[p])).rows[0].n,0);assert.equal((await db().query('SELECT count(*)::int n FROM import_preview_versions WHERE import_job_id=$1',[u.body.id])).rows[0].n,2);assert.equal((await commit(p,u.body,v.body)).body.state,'succeeded');});
test.after(()=>closeDb());
